### ISSUE TITLE
[Mac]Cpp Tests->Node : Sprite3D -> Testing Sprite3D: sprites added seems to be wrong 

### ISSUE THREAD

**Issue by samuele3hu** [cocos2d/cocos2d-x#10016]
The display as follows:

![347b5753-e84c-47c4-b6f6-f32e38305236](https://cloud.githubusercontent.com/assets/4231014/5751908/6920fbec-9ca6-11e4-8fd7-dcccebab35fc.png)

The sprite highlighted in red has shadow.

**Comment by super626** [comment]
The fade in and fade out is modifying the transparent of the plane.
We should sort the transparent object from back to front in order to render it correctly. However, you can not have correct result for some objects have the intersection parts unless you sort the triangles, as you know that sort the triangles is cpu cost work.

So it can not be solved recently.

**Comment by super626** [comment]
@samuele3hu @walzer @minggo

**Comment by drelaptop** [comment]
@can't reproduce this issue by cocos2d-x 3.17, so close. 

please reopen if you reproduce it using GitHub latest code. @samuele3hu @super626
