### ISSUE TITLE
Make it available as a Fragment in android instead of Activity?

### ISSUE THREAD

**Issue by sbhhbs** [cocos2d/cocos2d-x#10061]
We're writing a android app that really like to leverage the power of cocos2d-x. But since it's an app, we would like to have it as a fragment.

**Comment by walzer** [comment]
You can custom cocos2d-x to fit your requirement. Perhaps people in the forum could have some experiences on it.
I would deny this request in cocos2d-x main repository, because it's not a common requirement of game development.

**Comment by intmainreturn00** [comment]
Does something changed since than?) 
It really quite interesting case for android: you can collect power from both worlds) i.e. hundreds of android ui libs for simple tasks and something like spine animations from cocos2dx. I saw only one way how I succeed in accomplish that - I started cocos at android service and render to popup window above the default android layout, but it has obvious limitation.

**Comment by sbhhbs** [comment]
@lifeisdream check out this project https://github.com/sbhhbs/Hello-LWF-Cocos2d-x  it made it a fragment. the code is relatively old though.

**Comment by intmainreturn00** [comment]
Yeap) I was currently watching it while you post the link =) thanks. Lets see how its production ready)

**Comment by intmainreturn00** [comment]
For my purpose it did't get it. I need spine. And cocos version from that project (3.3 i guess) crash sometimes with spines.

So after one and a half days rewriting cocos\platform\android\java\src\...libs so it worked with cocos 3.15.1 and at the end I made viewpager with regular android Fragments as well as one Fragment with cocos surface view inside it. It unbelievable =)) but it works! and my spine animations.
Now, I think that I can comment some features, like audio engine and video view in order to compile with fragment and not with activity...so maybe now I should find a way to return them back. 

Its really really impressive, when you can start full body 2-3d engine as a android layer component like fragment. Can't wait to use it in some pretty material app =)


![device-2017-06-08-162331](https://user-images.githubusercontent.com/1473995/26936507-89febdd0-4c77-11e7-926b-bcc2a09221f1.gif)

**Comment by vkreal** [comment]
@lifeisdream Awesome job! I am really interested in doing the same thing having cocos run inside a fragment. Did you use https://github.com/sbhhbs/Hello-LWF-Cocos2d-x as a guide? Do you have any recommendations?

Thanks!

**Comment by intmainreturn00** [comment]
@vkreal I will try to write a plain guide and post all sources to github in a few weeks (and hope make more stable version with enabling audio and check that as mush staff working).
I used Hello-LWF-Cocos2d-x as a reference, but It used really old cocos so you need to rewrite some code at platform plugins. I have some experience working with cocos2dx from android Service, so I guess it helped me.

**Comment by vkreal** [comment]
@lifeisdream that be awesome to see how you did it! Very slick demo you posted above :)

**Comment by intmainreturn00** [comment]
made it even cooler - checkout the [sources](https://github.com/intmainreturn00/CocoSlice)
and without the need to change cocos. 
![results](https://user-images.githubusercontent.com/1473995/55374699-16b14780-5512-11e9-9aaa-d796b33abb4c.gif)

**Comment by yongjun123** [comment]
Really, this error occurs？   ERROR: Could not get unknown property 'PROP_BUILD_TOOLS_VERSION' for object of type com.android.build.gradle.LibraryExtension.   COOCS 3.17.1

**Comment by yongjun123** [comment]
How can it not run?

**Comment by intmainreturn00** [comment]
@yongjun123 you are talking about my library or something else? 
If your reply relates to my library please make an issue in corresponding repo.
If this relates to your own attempts to run cocos from fragment, if you share your code I could try to see what the problem is.

**Comment by yongjun123** [comment]
Can't run   CocosSilce ？   Cocos ：3.17.1     Android  NDK 16   Gradle build 3.1.1

**Comment by yongjun123** [comment]
Anything to pay attention to CocosSilce?  Can't run？

**Comment by yongjun123** [comment]
CMake Error at CMakeLists.txt:132 (setup_cocos_app_config):
  Unknown CMake command "setup_cocos_app_config".
