### ISSUE TITLE
Please update download-deps.py version when release v3.4

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#10080]
v3-deps-32.zip contains old header files for libwebsockets for WP8 and WiNRT. Please update the version so the correct files will be downloaded.

**Comment by minggo** [comment]
@andyque 
Is it true?

**Comment by zilongshanren** [comment]
@minggo 
Yes, @stammen  send a new PR after we publishing the tag. Could we change it now?

**Comment by minggo** [comment]
@stammen 
Because it is a pain to release a new version of updating deps. It means every one should download about 70+M libraries, it is a long time in China. And we will release new version of cocos2d-x on Jan.23, so i think we can release v3-deps-33.zip when we release it.

Please let me know if it is acceptable?
Thanks.

**Comment by stammen** [comment]
As long as you do not release v3.4 without updating download-deps.py to v3-deps-33.zip it is fine with me.

**Comment by minggo** [comment]
@stammen 
We will update it.
Just not want to update it so frequently.

Thanks for your mention.

**Comment by stammen** [comment]
OK. Thanks!

**Comment by minggo** [comment]
@stammen 
It is updated.

**Comment by stammen** [comment]
Thanks! websockets are now working for WP8.
