### ISSUE TITLE
[linux ios etc] outline is wrong for sprite3D

### ISSUE THREAD

**Issue by dabingnn** [cocos2d/cocos2d-x#10176]
![screen shot 2015-01-22 at 3 55 49 pm](https://cloud.githubusercontent.com/assets/4794489/5852304/60f01daa-a24f-11e4-9fa1-111cf64c812f.png)

**Comment by dabingnn** [comment]
@darkdukey @ricardoquesada @super626 
This issue does not exist in 3.3final and 3.4beta0, the outline error plane is a transparent one. I think it is a bug of renderer in current v3.4 branch.

**Comment by darkdukey** [comment]
I briefly investigated this. It's because depth write was off when rendering the spaceship
It only happens to the fade effect, because the fade effect change the alpha which set transparency flag of the RenderCommand which turn off the depth write as a result.

Fade effect -> Sprite3D->setTransparent -> RenderCommand -> setTransparent -> DepthWriteOff

Haven't thought of a good solution.
