### ISSUE TITLE
Refactor external folder structure

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#10304]
In current structure, cocos2d-x should include many header search paths. And it is hard to use the header files in source codes. 

Take png for example, it is used like

```
#include png.h
```

It is better to use like

```
#include png/png.h
```

**Comment by reagentoo** [comment]
But standart path for png in many linux distros is just png.h.

ls -l /usr/include/png.h 
lrwxrwxrwx 1 root root 14 янв 23 16:04 /usr/include/png.h -> libpng16/png.h

I have a nearly complete cocos2d-x package for Gentoo. But I can't finish it because of the many similar problems in the source code and in build system of cocos.

**Comment by minggo** [comment]
@reagentoo 
We will make all platforms use the same way.
The benefit is that, there is less header files to be included, and it will not cause conflict if different libs have the same header file name.
