### ISSUE TITLE
Label crash getString()/setString()

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x#10333]
Hi, I've made an empty project using cocos studio 2.1 and added to scene a label. But I can't change or get it's contents from code:

```
Label* label = static_cast<Label* >(rootNode->getChildByName("Text_1"));
    label->setOpacity(128);
    std::string str = "Foobar";
    label->setString(str);
```

and I'm getting this exception: 
[Imgur](http://i.imgur.com/O94hxZR.png)
As much as I understand this error it says that something is null and cannot be accessed. However label is not null, because if I comment last line it works and opacity is label is changed.

The same result on getString(). I also tried adding simple font (arial.ttf) and it still crashes. 
This errors appears on both cocos2d-x 3.3 and 3.4 and also both windows and mac.
Is it a bug or I'm missing something?

**Comment by lalaloha** [comment]
no. this is not a bug. you're typecasting a "cocos2d::ui::Text *" type to "cocos2d::Label *" type, because of that it will crash. Simply typecast it to "cocos2d::ui::Text *" will solve the problem. cocostudio is using "cocos2d::ui::Text *" class if you're using the "Label" widget. I think you need to include "ui/CocosGUI.h"

**Comment by piotrros** [comment]
Wow thanks. I never though something named Label is not a Label, but Text class. This was very confusing.

**Comment by hgokturk** [comment]
I am getting "namespace cocos2d::ui has no member Text" error in a similar case. Any idea why?
