### ISSUE TITLE
CCArmature Rendering Issue 

### ISSUE THREAD

**Issue by ruhen** [cocos2d/cocos2d-x#10397]
![qq 20150206144404](https://cloud.githubusercontent.com/assets/7741860/6075521/00a2c008-ae0f-11e4-9bb3-053f4864b3a0.jpg)

my cocos2dx version is 3.2,  as the image show ,my ccarmature will not be rendered sometimes ,especially in the release mode on IOS

**Comment by ruhen** [comment]
debuging this problem for a long time,and i found that  in the "Texture2D::initWithMipmaps" function OpenGL gives an error.:
      Texture2d:uploading compressed texture level:0 . glerror 0x0502
 glerror 0502  meas GL_INVALID_OPERATION  ,now, how to fix this bug?

**Comment by Hioln** [comment]
I also meet this problem, any suggestion??

**Comment by minggo** [comment]
@chengstory 
Could you please take a look?

**Comment by dannyjiajia** [comment]
I also meet this problem, any suggestion??

**Comment by pandamicro** [comment]
Delayed to v3.8

**Comment by xiaofeng11** [comment]
Hi, ruhen
Cocos2dx v3.8 & CocoStudio 2.3.2 have rewrite some armature animation code, and Cocostudio support import & editing 1.6 armature animation, please test in new version. If there still have bug, please provide us a sample project to test it, because we won't have a project to reappear this problem.
