### ISSUE TITLE
Silent gap when looping audio with the new audio engine on Android

### ISSUE THREAD

**Issue by maltium** [cocos2d/cocos2d-x#10527]
In cocos2d-x v3.4, when using `AudioEngine::play2d("sample.ogg", true)` you can hear a silent gap each time the clip ends/starts.

This makes it impossible to create a seamless audio effect and instead sounds like the game is stuttering.

**Comment by jimrange** [comment]
I looked into this, but was unable to find a fix.

The audio file I was using is a 44.1KHz 8-bit mono wave file with a perfect seamless loop when played on iOS, Android 4.x, and Mac.

At the time of the stutter, this logcat message is printed:
`I/NuPlayer(  184): audio discontinuity (formatChange=0, time=1)`

I reviewed the OpenSLES specification 1.0.1. 
There does not seem to be anything setup wrong in the current code that would cause the stutter.

Tried to pass a specific end time for the loop by getting the duration:

```
    SLmillisecond msec;
    result = (*_fdPlayerPlay)->GetDuration(_fdPlayerPlay, &msec);
    if(SL_RESULT_SUCCESS != result){ ERRORLOG("get track duration failed"); break; }
    cocos2d::log("audio track msec:%.2f", msec);
```

But the duration msec returned from GetDuration is -1 for some reason.

Verified in the OpenSLES 1.0.1 spec that endPos is the position in milliseconds relative to the beginning of content specifying the end the loop. endPos must be greater than startPos. A value of **SL_TIME_UNKNOWN** denotes the end of the stream.
So that should be ok to pass SL_TIME_UNKNOWN for endPos.

Tried just changing the startPos which is set to 0 to other values like 0.01, 0.1, and 1.0 just to see what would happen. The gap in the loop still occurred.

Modified the code to check if SetLoop returns SL_RESULT_SUCCESS. It does.        

```
_loop = loop;
if (loop){
    result = (*_fdPlayerSeek)->SetLoop(_fdPlayerSeek, SL_BOOLEAN_TRUE, 0, SL_TIME_UNKNOWN);
    if(SL_RESULT_SUCCESS != result){ ERRORLOG("set loop failed"); break; }
}
```

This gap in the loop does not occur in SimpleAudioEngine, but it does in AudioEngine.  
More info: http://discuss.cocos2d-x.org/t/looping-gapless-audio-effects-on-android/20006/5

**Comment by netunlimited** [comment]
A similar gap on Android occurs when using the setFinishCallback to play a next sound. On iOS this works fine, on Android there is a noticeable bigger gap in between the sounds.

**Comment by dumganhar** [comment]
Similar issue with https://github.com/cocos2d/cocos2d-x/issues/16144.
I was fixed at the latest code of v3 branch. Plz have a try.
The patch will be in v3.13 if you could wait.

Currently, we encapsulate a `PcmAudioPlayer` for playing small audio file, it's perfect to loop a music without any gaps.

Therefore, I closed this issue. And feel free to re-open it if you find any problems.
