### ISSUE TITLE
lua bindings - cc.Label:createWithTTF is missing

### ISSUE THREAD

**Issue by hamburml** [cocos2d/cocos2d-x#10538]
Hi.

FontTests for lua is using createWithTTF.

CocosCodeIDE isn't showing createWithTTF when typing cc.Label:
It only shows create(), createWithBMFont() createWithCharMap() and so on...

**Comment by walzer** [comment]
Code IDE v1.x still has some bugs like this one you described.
We're testing IDE v2.0 based on IntelliJ, which will bring better user experience to everyone. Due to IDE v2.0 is very close to its release, I have no plan to fix bugs in IDE v1.x because they are totally different technical resolutions, one is based on Eclipse and 2.0 is based on IntelliJ.
