### ISSUE TITLE
Where is the "editor-support/cocostudio" in V4?

### ISSUE THREAD

**Issue by stonejiang208** [cocos2d/cocos2d-x#10869]
HI, all.
   I upgrade the cocos2d-x to v4-developer, but I can not find the "editor-support/". And the test codes about "cocos studio"  in  TestCpp does not exist.
  Is the v4 will remove "cocos reader"?  

Thanks.

**Comment by walzer** [comment]
Good question. I had an argument with Ricardo. His opinion is that the quality of studio reader is very bad and it breaks the quality of cocos2d-x, so in v4, the studio related code has been removed. My idea is that, we had to improve it but not remove it. A game engine should have an official editor support in these days.

Since we suspend v4 plan and back to work on v3, the editor-support/cocos studio is back. And I won't remove it away in the future. Actually, our dev team in Chengdu China is improving the reader currently.
