### ISSUE TITLE
why remove the feature of debug with cocos code IDE in v3.5?

### ISSUE THREAD

**Issue by flamefox** [cocos2d/cocos2d-x#11204]
before 3.5 I can use 
`-workdir $(ProjectDir)../../../  -debugger studio` for remote debug
or just debug in  cocos code IDE

the code 3.4final

``` C++
#if (COCOS2D_DEBUG > 0) && (CC_CODE_IDE_DEBUG_SUPPORT > 0)
    // NOTE:Please don't remove this call if you want to debug with Cocos Code IDE
    RuntimeEngine::getInstance()->start();
    cocos2d::log("iShow!");
#else
    if (engine->executeScriptFile("src/main.lua"))
    {
        return false;
    }
#endif
```

3.5:

``` C++
    if (engine->executeScriptFile("src/main.lua"))
    {
        return false;
    }
```

and not include any runtime

can any one tell me why?

**Comment by hamburml** [comment]
I would really like to know that, too!

**Comment by SunLightJuly** [comment]
Codes of runtime have been removed from cocos2dx 3.5. Please use the product "cocos" to support cocos code IDE.

**Comment by hamburml** [comment]
How can I update a cocos code ide cocos-source 3.4 project to 3.5 framework?

_edit_

I created a new project with 3.5 framework and copies my lua-files in it. It is working BUT the particle bindings were removed. I tried to add them but I can't because the generate-bindings-tool isn't working. Please read here: http://discuss.cocos2d-x.org/t/error-when-executing-genbindings/15336/2

**Comment by hamburml** [comment]
@SunLightJuly I am using 3.5 framework but i am unable to debug with cocos code ide a lua project.
Any ideas?

**Comment by walzer** [comment]
Well, many users are complaining this. The similar issue ##11339
We have already fixed this, added template/lua-runtime back in v3.6.
