### ISSUE TITLE
why remove lua-template-runtime in 3.5?

### ISSUE THREAD

**Issue by dantezhu** [cocos2d/cocos2d-x#11339]
why remove lua-template-runtime in 3.5?

i want create proj in cocos code ide with 3.5, but it will blocked.

if I use cocos, the proj it created is only libs, the call of print will never show.

so, I dont understand why do you remove lua-template-runtime?

**Comment by walzer** [comment]
Well, good question.
- Before, we have cocos2d-x, cocos2d-js, and merge them into cocos framework, which works together with cocos and code ide. Some colleagues idea is that, editors support is something outside the scope of cocos2d-x, so they removed lua-template-runtime because it works only for code ide
- We have already fixed this mistake in v3.6. Cocos2d-x should have solid editor support, including cocos studio and cocos code ide.

So today, if you're looking for a solution to use cocos2d-x lua with code ide, please visit download.cocos.com. Or use our latest v3.6.

Thanks for your feedback.
