### ISSUE TITLE
Add AnySDK framework, to replace but keep compatibility with plugin-x

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#11561]
We had better to unify the plugin-x API, especially AnySDK framework is becoming more popular in China. And the meantime, US colleagues are developing SDKBox.

Could we merge these products and API, and offer it officially in cocos2d-x framework?

**Comment by linshun** [comment]
The framework of AnySDK frontend could be merged with Plugin-x. 
I don't think SDKBox could be merged with Plugin-x.

Before we merged the framework of AnySDK, it is better to create a PRD in google docs.

**Comment by zj8487** [comment]
+1 replace but keep compatibility

**Comment by pandamicro** [comment]
I think we should have a complete product design and target definition for this task.
- First of all, what's the difference between Plugin-x, SDKBOX, AnySDK ?
- How to merge AnySDK & SDKBOX ? With source code or prebuilt library ?
- How to solve the difference between SDKBOX & AnySDK ? They have different API, client application, integration instruction.
- How to keep compatible with Plugin-x and old projects using Plugin-x ?
- Most important, what's the detailed target of this task ? Who should define it ? Who is the owner ?

@walzer @darkdukey @hylthink

Before this task been clarified, I will move it to next milestone

**Comment by darkdukey** [comment]
- Plugin-x: old attempt to create plugin for cocos2d-x nobody is maintaining it now, and it's seriously out of date, I highly doubt it will be missed if we remove it since most of them are barely working.
- SDKBOX: a package manager for third party SDKs, actively maintained and super easy to use.
- AnySDK: very good product, but right now only focus on chinese market

Firstly I don't think the compatibility with Plugin-x is that important, because it's pretty broken and not many developer are using it.

I think it's fine to replace Plugin-x with AnySDK, but AnySDK seriously need to do a better job in terms of localization so developer from other country can use it.

I think moving forward, the best way is to break the dependency between engine and third party SDKs, because for the developers they might want to use a old version of the engine because of stability, the old version of third party SDK that come with the engine will be seriously out of date. Like what we did now. I think break things down into engine and plugins makes the most sense. So in this case, we can just ship Cocos2d-x with SDKBOX, and developer can install any plugin they want (AnySDK can be a plugin as well), and they'll always get the latest plugin because SDKBOX keeps everything up to date.

**Comment by pandamicro** [comment]
>  (AnySDK can be a plugin as well),

I really like this idea !
AnySDK plugin need to be installed manually now, and SDKBOX can solve it.

In my comprehension, AnySDK / SDKBOX are different products:
- SDKBOX should be able plug any kind of 3rd party library into user project. 
- AnySDK wrapped many SDKs APIs into AnySDK API and delegate their functionalities.
- Both of them are targeted to a general usage, should not be limited to one engine.

Is that correct ?

**Comment by darkdukey** [comment]
Yes that's correct, there is plan for SDKBOX support other engine, adobe air, unity as well.

**Comment by hylthink** [comment]
AnySDK can be a plugin as well.So the tool is under development to solve it that AnySDK plugin need to be installed manually, it bases on 'cocos package’.

The tool will be integrate into AnySDK client in next version.

AnySDK
黄艳丽

**Comment by darkdukey** [comment]
@hylthink do you know who is maintaining `cocos package` right now? As far as I know `cocos package` are no longer been maintained, and the original maintainer joined SDKBOX team.

**Comment by hylthink** [comment]
I am not quite clear about it. Maybe junfeng zhu is  maintaining cocos package right now.

**Comment by minggo** [comment]
AnySDK is integrated with creator, so i thin we can close this issue.
