### ISSUE TITLE
Improve SpritePolygon

### ISSUE THREAD

**Issue by walzer** [cocos2d/cocos2d-x#11568]
- Currently, SpritePolygon's vertices are inner vertices, this is good for some use cases, but will noticeably cut into sprites if the vec count is low. To Fix: figure out a new way to generate outer vertices, so sprite look the same.
- Plan to merge with normal Sprite
  This will probably performs better in most cases. The idea is that if normal sprite is created and that file and rect exists in `SpritePolygonCache`, then the normalSprite will use TrianglesCommand instead of quad command. Then we should also design and add a fileformat to save and load data from `SpritePolygonCache`

**Comment by Wu-Hao** [comment]
- Currently, SpritePolygon's Marching Square algorithm takes the whole image into account, where it should only take the specified rect into calculation. Fix marching square so that it only takes specified rect into account not the whole image.
- SpritePolygon should also support setTextureRect at runtime, it should look for the rect in cache.
- PolygonInfo struct should be created inside the cache class, to avoid data copying
- Marching Square, Poly2tri, RDP should be moved to CCUtils, so other class could use those functionality

**Comment by zilongshanren** [comment]
@Wu-Hao
Maybe SpritePolygon should support more texture pixel format, now only RGBA8888 is allowed. But RGBA8888 consumes a lot of memory, many game developers prefer to RGBA4444 format with dithering enabled.

**Comment by Wu-Hao** [comment]
- Currently, SpritePolygon's Marching Square algorithm takes the whole image into account, where it should only take the specified rect into calculation. Fix marching square so that it only takes specified rect into account not the whole image.
- SpritePolygon should also support setTextureRect at runtime, it should look for the rect in cache.
- PolygonInfo struct should be created inside the cache class, to avoid data copying
- Marching Square, Poly2tri, RDP should be moved to CCUtils, so other class could use those functionality

**Comment by pandamicro** [comment]
@fusijie what's the status about this issue? Can you add the related PR links in comment?

**Comment by fusijie** [comment]
@pandamicro  The main function is completed, now we are finding the bugs and making the test case.

we will send the pull request when the things mentioned above all completed.

**Comment by pandamicro** [comment]
Ok, thanks for the update

**Comment by pandamicro** [comment]
Related PR: https://github.com/cocos2d/cocos2d-x/pull/12243
