### ISSUE TITLE
EditBox InputFlag::PASSWORD iOS issue

### ISSUE THREAD

**Issue by MrCapone** [cocos2d/cocos2d-x#11732]
On iOS when i set editBox->setInputFlag(EditBox::InputFlag::PASSWORD); i can't cancel this. Even if i set another InputFlag, EditBox will hide all input.

**Comment by Mazyod** [comment]
Yes, I think it was by design that you can't change it later, maybe for security reasons. Can you please explain why you would want to change a textfield from plain text to Secure Input, then back again?

**Comment by Mazyod** [comment]
There are many apps that provide a "show password" icon, where the user has the ability to reveal the password they typed, so they can make sure they are typing it correctly, since it is sometimes hard to get right on mobile. Maybe that was the use case?

It should be easy to accommodate on iOS and Mac. I am thinking, just add a `InputFlag::PLAIN_TEXT` enum value, and switch back to plain text from there.

**Comment by Mazyod** [comment]
@zilongshanren Can someone confirm if this is a bug/feature request? It's easy to fix, I can submit a PR using the solution described in previous comment.

**Comment by zilongshanren** [comment]
@Mazyod In my opinion, I think it could be  a bug fix. But we should also consider the multiple platform implementation, especially for Android.

**Comment by Mazyod** [comment]
@zilongshanren thanks, I think I can deal with that as well. Will try to submit something very soon

**Comment by zilongshanren** [comment]
@Mazyod  Great :+1:

**Comment by Mazyod** [comment]
@pandamicro I hope there wasn't any confusion about my previous PR. I didn't fix the bugs listed, since we decided to create separate PRs for each one. The PR was just cleanup work to prepare for future improvements

**Comment by pandamicro** [comment]
Sorry, my bad
