### ISSUE TITLE
onKeyPressed() never gets called for Android hardware buttons

### ISSUE THREAD

**Issue by jphw** [cocos2d/cocos2d-x#11746]
In TouchesJni.cpp in function Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeKeyDown, when EventKeyboard is being created - it always gets "false" as "isPressed" argument. As a result of that - user can only detect Back button press by overriding onKeyReleased() of a Layer or by settings onKeyReleased callback in EventListenerKeyboard. But onKeyPressed will stay silent. 

This is counterintuitive and i couldn't find any documentation saying that in case of Android hardware buttons i should avoid using onKeyPressed and use onKeyReleased instead

**Comment by ahmed-belal** [comment]
Because onKeyPressed never gets called there is no way to implement a "key is held down right now..." logic, and also that only one key event is being delivered, i.e. if you were to create a game where you could move the character with arrow keys you can only go up, down, left or right at a time, not diagonal.

On mobile devices such controls are not usually required but if a developer wants to convert their game for the Chrome web store then usually you'd want a keyboard control, not touch/mouse control. This is where the problem arises the most.

Is there any other way to catch a key pressed or key down event on Android? A patch perhaps?

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@jphw
