### ISSUE TITLE
prebuilt 不支持 visual studio 2013 express

### ISSUE THREAD

**Issue by XiaochenFTX** [cocos2d/cocos2d-x#11865]
win8.1 使用 gen_prebuilt_libs.py 无法执行构建
查了一下代码，
commandPath = os.path.join(vsPath, "Common7", "IDE", "devenv")
这句出的问题
因为express版本vs并没有devenv.exe

**Comment by syswow** [comment]
我也在用VS 2013 express for Desktop，这个版本IDE是`WDExpress.exe`

**Comment by natural-law** [comment]
@XiaochenFTX 
Does `gen_prebuilt_libs.py` means the file `tools/gen-prebuilt/gen_prebuilt_libs.py`?

I'm sorry that it has been removed in version v3.8.
Please use command `cocos gen-libs` instead. 
Here is the manual of the command: http://www.cocos2d-x.org/wiki/Cocos_gen-libs

The implementation of `cocos gen-libs` is using `msbuild` instead of `devenv`. Hope it's helpful.
