### ISSUE TITLE
PhysicsBody does not work with negative scales cocos2d-x 3.6

### ISSUE THREAD

**Issue by Dredok** [cocos2d/cocos2d-x#11955]
Hi,
I have a character made of a hierarchy of bones and sprites. I want to use shapes from chipmunk in order to setup the physics. I use rogue bodies and everything works okey.
Until I try to flip the sprite setting scaleX to -1.0f. Then the shapes do not update properly to the new transform, they change the scale but they not change the positions according to the hierarchy.

I have seen there is an old bug related to this but it's apparently not fixed yet. Any workarounds?

**Comment by Dredok** [comment]
You can see a picture with the image without scaling and one with scaling:

![image](https://cloud.githubusercontent.com/assets/1898021/7759563/d2dfff18-0012-11e5-8aea-94ec0f03673f.png)

![image](https://cloud.githubusercontent.com/assets/1898021/7759554/beb7dd4e-0012-11e5-806a-d0568c8e7d35.png)

**Comment by Dredok** [comment]
This still happens in 3.7

any plan to fix it soon?

**Comment by ricardoquesada** [comment]
thanks. scheduled for v3.8

**Comment by ricardoquesada** [comment]
@Dredok were you able to solve this? what did you do?

I couldn't find a good solution for this one. Probably the solution is to remove existing shapes and replace them with new ones that are flipped.
But I don't think we should add that complexity in cocos.... or perhaps we should, but at the moment I can't find that it will add a lot of complexity for a use case that is not that common.

**Comment by Dredok** [comment]
I can not remember the workaround but I did not make any fix to the code, so I guess I just used different shapes.

**Comment by ricardoquesada** [comment]
thanks. I'll mark this issues as won't fix due to its complexity to fix and that in only affects a very small percentage of the use cases.

have two shapes defined by the user should be the correct way to fix it.

why is it complex to fix it:
- there is not such "flip" shapes in chipmunk so we have to implement it ourselves
- the new shapes should be created in the correct order (counter clockwise? or was it clockwise?)
- it could be expensive to do it... assume that you have 500 sprites and you flip them at the same time
- it takes memory and the sprites should hold up to 4 different shapes: XY, -XY, X-Y, and -X-Y.

So, this is "won't fix" because I don't know how to do it in a correct way... but feel free to reopen it if you know how to fix it in an elegant way that won't affect performance and memory.
