### ISSUE TITLE
AudioEngine's bug

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12254]
Code in cocos2d-x v3.4 HellowWorld:

``` cpp
void HelloWorld::menuCloseCallback(Ref* pSender)
{
    experimental::AudioEngine::stopAll();
    experimental::AudioEngine::play2d("click_level1.mp3", false);
    experimental::AudioEngine::play2d("buttonClick.mp3", false);
    experimental::AudioEngine::play2d("wind_level1.mp3", true);
    return;
}
```

When I click on the menuClose button repeatedly fast, wind_level1.mp3 have more probability not looping play. Click slowly when less probability.

**Comment by dumganhar** [comment]
@folgerhu, sorry for my late reply.
Could you tell me which platform you tested on?
It seems to be a platform dependence problem since AudioEngine is implemented separately.
I assume you got the issue on Android. I've already refactored AudioEngine for Android platform.
It will be appreciated if you could pull v3 branch to test this issue again.
I closed this issue temporarily, feel free to re-open it if it was fixed. Thanks.
