### ISSUE TITLE
FontAtlasCache::releaseFontAtlas() need fault-tolerant

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#12616]
RefPtr < widgets > gWidget, the gWiget tree contains the ui::Label objects, when the end of the program:
1. _atlasMap first be destructor, this variable is void
2. to gWidget destructor, ui::Label destructor
3. ui::Label destructor sort used static FontAtlasCache: : releaseFontAtlas(), access to _atlasMap inside
4. but because _atlasMap is invalid, the program will be crash

``` cpp
bool FontAtlasCache::releaseFontAtlas(FontAtlas *atlas)
{
    if (nullptr != atlas)
    {
        for( auto &item: _atlasMap )
        {
            if ( item.second == atlas )
            {
                if (atlas->getReferenceCount() == 1)
                {
                  _atlasMap.erase(item.first);
                }

                atlas->release();

                return true;
            }
        }
    }

    return false;
}
```

Note: All similar Cache should need this kind of fault tolerance

**Comment by yangws** [comment]
Apply RAII mechanism on static class instances are unsafed practice.
The reason is C/C++ runtime ensure all static class instances will be destruct, but not ensure the destruct order is suitable.
In this issue, _atlasMap and gWidget are static class instances, and they are continers. For the reasion we talked above, they will be destruct on app termination, but the destruct order is uncertain. 
The _atlasMap destruct before gWidget, which contain a label instance will cause segment failt.
The code should ensure all label instances should be destruct before the _atlasMap destruction.
As a example, FontAtlasCache has a method called purgeCachedData for destruct all instances  at right moment.
So gWidget should destruct the instance, which contain in it, at right moment, in other worlds, the label instance which contains in gWidget should be destruct before the destruction of gWidget.
