### ISSUE TITLE
Add some 3D show cases

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#12665]
We can buy some resources to build up some 3D show cases with great visual effects

Proposed features
- [ ] Light Map
- [ ] Water
- [ ] UV animation
  etc...

**Comment by super626** [comment]
@pandamicro 
light map, uv animation already exist.
We do not have water in the sprite3d test until now. However, we can move the water from FantasyWarrior to the sprite3d test.
The problem is that many user do not know about that.
Maybe we need some course to help the user to understand and use it.

**Comment by pandamicro** [comment]
But the test in the current test cases are really ugly, it can't show how great our technique can do.

**Comment by yixiaoqingyuz** [comment]
The current light map  test cases is a fake lightmapping.
It is just a baked light texture.
