### ISSUE TITLE
TestJavascript gives vm_protect error.

### ISSUE THREAD

**Issue by pilwon** [cocos2d/cocos2d-x#1268]
I tried running the latest TestJavascript project in cddbc7287ad2f04d13e3e50b7ce5e25e6aa92797 but it only works in the simulator. I get the following error when I try to run it on device:

```
dyld: vm_protect(0x00001000, 0x0085A000, false, 0x07) failed, result=2 for segment __TEXT in /var/mobile/Applications/B8F3BF2E-3EDC-487B-BE98-784DB2268838/TestCpp.app/TestJavascript
```

**Comment by dgileadi** [comment]
I have this same issue.  Did you find a workaround?

**Comment by amittmahajan** [comment]
@dgileadi Seems like you may be able to fix this by changing the compiler to GCC 4.2

**Comment by rboyd** [comment]
+1 still an issue when generating Xcode project from cocos2dx_js template. Works fine in simulator. When I target iOS device I get this error.

Strangely, cocos2d-x/samples/Javascript/TestJavascript/proj.ios/TestJavascript.xcodeproj works fine on device and simulator (unchanged -- with LLVM setting).

In my generated project when I switch to GCC 4.2 I get compile errors in jsapi.h:

```
/testproj/libs/javascript/spidermonkey-ios/include/jsapi.h:919: Template argument 1 is invalid
/testproj/libs/javascript/spidermonkey-ios/include/jsapi.h:919: Expected `{' before '>' token
/testproj/libs/javascript/spidermonkey-ios/include/jsapi.h:919: Expected unqualified-id before '>' token
```

and Root.h:

```
/testproj/libs/javascript/spidermonkey-ios/include/gc/Root.h:107: Invalid use of incomplete type 'class js::HandleBase<JS::Value>'
/testproj/libs/javascript/spidermonkey-ios/include/gc/Root.h:71: Declaration of 'class js::HandleBase<JS::Value>'
```

**Comment by dumganhar** [comment]
Hi all,
I think it's a bug of the LLVM compiler. If you build your application in `Release` mode, and run it on device.
It will work without any problems.
But the problem is that if we set the default value of `Optimization Level` to `-O0`, it will trigger `vm_protect` errors.
Before, we switch the compiler to GCC avoid this issue when debugging app on device.
But after i upgraded the spidermonkey library to Firefox v18.0, there are some compilation errors by `GCC` compiler.

##### So in the latest code on the github we set the `Optimization Level` to `-O1`, and in this way, the issue is  resolved.

Could all of you try it in this way? And give us the feedback?
Or could you guys find out the reason? Thanks a lot.

**Comment by rboyd** [comment]
Many thanks! It works beautifully with -O1.
