### ISSUE TITLE
cocos3.6 lua导出userdata安全检查问题

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#12969]
1. 在脚本运行过程中一不小心就可能引用了已经失效的userdata，比如在callback里面使用Node。在COCOS2D_DEBUG下是有安全检查的，但是到了release下就有可能导致crash，期望仅仅是脚本的异常。

期望将lua导出接口在任何build下面都可以有脚本的参数检查，至少是可选，而不是一刀切使用COCOS2D_DEBUG来控制。

**Comment by c3076802** [comment]
因为开发过程中，脚本程序员未必很清楚C++对象的生命周期，C++对象生命周期检查还是重要的。尤其这种问题大多是延时调用才会出现

**Comment by flamefox** [comment]
should try tolua.isnull

**Comment by pandamicro** [comment]
If you want to reference to the node you stored, you'd better use `setUserObject` instead of `setUserData`. The memory of data in user data should be managed and tracked by yourself, in contrary, user object will be referenced by the owner and won't be released.

If you have further informations please reopen it

**Comment by dumganhar** [comment]
> 期望将lua导出接口在任何build下面都可以有脚本的参数检查，至少是可选，而不是一刀切使用COCOS2D_DEBUG来控制。

@pandamicro , I also think it's an issue, we should not use `COCOS2D_DEBUG` for safe check in lua bindings code. 
Probably, 3.x should use `TOLUA_RELEASE` or another macro for checking.
IMO, the argument invalid checking will not waste too much time, for the `procedure haleness` is more important. **We should not make engine crash for games developed by `Lua` or `JS`**.

**Comment by pandamicro** [comment]
> I also think it's an issue, we should not use COCOS2D_DEBUG for safe check in lua bindings code. 

I don't think safe check is the correct way for the mentioned issue, of course safe check can avoid crash, but released node can't be restored by safe check. The real reason of this issue is that _userData is a void\* pointer and won't be retained by the owner, instead _userObject will, that's the reason I suggested to use _userObject. In this way, the stored Node won't be released by auto release pool.

> We should not make engine crash for games developed by Lua or JS.

This is another discussion which won't have a result without concrete use cases. For the case this issue mentioned, I still think crash is not a problem because the object is already released. The real problem is that our C++ objects and script objects life cycle isn't the same.

**Comment by c3076802** [comment]
Yes, I do agree with @pandamicro, 
    The real problem is that our C++ objects and script objects life cycle isn't the same.

But the problem is in fact more complicated.

quote for issue #13072 

> 这是在开发中很常见的问题，说白了很多脚本程序员基础本来就不太好，我知道如果retain和release都弄好，其实是不会有以上的问题，但是现实就是根本上无法控制，记得retain又忘了release，造成内存泄露。
> 
> 之前我们做过端游，就直接导出智能指针，这样就没有这种问题了，比如BigWorld, 用得是python
> 但是lua 5.1 table的没有gc事件（5.2有），这样就没办法精确控制C++对象的生命周期，而且就会导致内存消耗变大，这个在手游是不允许的。
> 
> 在开发大型游戏时多人合作，在有限的开发时间里，对象生命周期及其难以维护，之前我们用cocos做的几个项目都是手改的，真心不想再弄一次了，蛋疼。

## 

## 现在各个平台都有崩溃率这个指标，搞不好就下架了。

> It is nearly impossible to catch the bug in DEBUG mode when you developing a large project.
> 
> some script programmer just don‘t have the capacity to handle the obj life-cycle well when developing module with others ( specially involving timer, callback and events push from the server)；
> and as you know we just not be able to hire good script programmer always; due to the budget and release deadlines. It is a practical problem.
> 
> We would like to have a safe and slow mode as Unity(C#) provided; 
> script exception is acceptable , crash is not.

##

**Comment by pandamicro** [comment]
We are investigating how to solve the retain/release issue in script, we'd like to remove them entirely in JSB

**Comment by c3076802** [comment]
Great ! 
I did have some experience of handling object that share between script and C/C++ , BigWorld with python, GameBryo with lua and wrapping early version of Irrlicht  with lua, might be helpful.
