### ISSUE TITLE
Scene Graph Listener should only receive Events for the node's camera

### ISSUE THREAD

**Issue by stevetranby** [cocos2d/cocos2d-x#13475]
I'm not sure if this is an issue or a design "feature" that needs change of documentation.

Because we'd have to check for visibility in many many places in our own code everywhere we have an "on" event based on scene graph priority I believe this is an issue and not a valid API or Engine change.

Our solution

``` cpp
/// CCEventDispatcher.cpp : Line 843
Camera::_visitingCamera = camera;
for (auto& l : sceneListeners)
{
    auto lCameraMask = l->getAssociatedNode()->getCameraMask();
    auto cameraFlag = (unsigned short)camera->getCameraFlag();
    auto canVisitFlag = ((cameraFlag & lCameraMask) != 0);
    // NOTE: protected
    //auto canVisit = l->getAssociatedNode()->isVisitableByVisitingCamera();
    auto canVisit = canVisitFlag;
    if (canVisit && onEvent(l))
    {
        shouldStopPropagation = true;
        break;
    }
}
```

**Comment by yangws** [comment]
Let us consider this situation:
- create a node named 3DSceneNode, then add a 3D sprite and a camera, which look at the sprite, into it, 3DSceneNode->setPosition(10000, 10000, 0)
- create a node named 2DSceneNode, then add a 2D sprite and a camera, which look at the sprite, into it, 2DSceneNode->setPosition(-10000, -10000, 0)
  Finally, we get a picture on screen, which contains a 3D sprite and a 2D sprite in it.

Let us touch the screen at Point(100, 100), how to judge which sprite we touched?
The function to decide the collision point in world is create a ray from camera location to the touch position on Near/Far plan, so the ray depends the camera's position. 

In above situation, because we have two camera, so we'll get two rays, one start at (10000, 10000, 0) and another start at (-10000, -10000, 0), to test 2D sprite and 3D sprite hitted or not seperately.

Due to every node add listener to EventDispatcher directory, so we had to loop all cameras when dispatch touch event to scene graph.

**Comment by stevetranby** [comment]
Correct, and I understand that part. 

Our issue was that we were getting two calls to our listener->onTouchesBegan callback method. 

```
auto listener = EventListenerTouchAllAtOnce::create();
listener->onTouchesBegan = [this](const std::vector<Touch*>& pTouches, Event *pEvent) {
  // called twice because we have 2 cameras in our scene
};
getEventDispatcher()->addEventListenerWithSceneGraphPriority(listener, this);
```

I've updated the title to better describe the issue we're seeing.

**Comment by pandamicro** [comment]
For now, we do dispatch events to all node for each camera, and event handling you can check wether the camera mask match and then handle it. like the following PR: https://github.com/cocos2d/cocos2d-x/pull/13557 which is also exactly what you are doing in your solution

The current implementation:
1. Event dispatcher loop all camera to dispatch the event
2. Each camera loop all node to dispatch the event

We are considering another solution:
1. Event dispatcher loop all camera to dispatch the event
2. Each camera loop all node and dispatch the event to the nodes which have the same camera mask

**Comment by pandamicro** [comment]
Done
