### ISSUE TITLE
Please add function addTexture(Texture2D *texture2D, const std::string &key) to TextureCache

### ISSUE THREAD

**Issue by kiranb47** [cocos2d/cocos2d-x#13568]
Which will be usefull to cache custom texture made using Render Texture.

**Comment by pandamicro** [comment]
I agree, it will be useful, @minggo what do you think?

**Comment by minggo** [comment]
The key of TextureCache is the full file path of the file that generating the texture, and it is used to prevent re-generating a texture again. So i don't think it is a good idea to have this function, because developers may pass wrong key.

And could you describe in what situation does addTexture used?

**Comment by Almax27** [comment]
I don't think this is necessary either as TextureCache already supports adding images via:
`Texture2D* TextureCache::addImage(Image* image, const std::string& key)`

And images can be obtained from a RenderTexture using: 
`Image* RenderTexture::newImage(bool flipImage = true);`

Also RenderTexture performs caching of it's texture using VolatileTextureMgr on EVENT_COME_TO_BACKGROUND and EVENT_COME_TO_FOREGROUND events anyway.

**Comment by kiranb47** [comment]
OK, it's not necessary if RenderTexture support exporting Image*
