### ISSUE TITLE
[Web] Add Wechat Audio support

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#13752]

**Comment by JethroSovr** [comment]
Does it support now?

**Comment by VisualSJ** [comment]
It has been supported.

**Comment by JethroSovr** [comment]
I have load the music res.test_music,
Then I used  "cc.audioEngine.playMusic(res.test_music,true);"  to play audio.
the web on Android is ok, it can autoplay and loop the music.
but web on iOS, it cant autoplay, when i touch screen,it playe once, and no loop , any idea?

**Comment by VisualSJ** [comment]
This is very helpless...

First, audio is divided into webaudio and dom.
Background music use dom playback.

For ios, music, which is played on the dom, must be the user's touch screen to play.
We don't recommend using webaudio here, because the memory consumption is too high.

If you want to try, you can put the `effect` code into `music`:

https://github.com/cocos2d/cocos2d-html5/blob/develop/cocos2d/audio/CCAudio.js#L726
https://github.com/cocos2d/cocos2d-html5/blob/develop/cocos2d/audio/CCAudio.js#L543

**Comment by JethroSovr** [comment]
My effect code is like this...
I set web on iOS music cant loop , only played once.Then touch screen it not play yet .
Any alternative solutions？ We want the background music loop play, not once.Thx for review.
