### ISSUE TITLE
c++_static over gnustl

### ISSUE THREAD

**Issue by zeyangl** [cocos2d/cocos2d-x#14116]
c++_static fixes a lot of C++11 compatibility issues in gnustl. It should be the default C++ library for cocos. SDKBOX uses gnustl as well, and should be fixed too.

**Comment by ricardoquesada** [comment]
thanks. could you put more details about it?  how should we use it? (a patch would be great)
thanks.

**Comment by minggo** [comment]
@ricardoquesada Just only modify `Application.mk`. I mentioned it to you and google guys about using `c++_static` instead, but you said google guys told you that it is not stable. Did you remember?

**Comment by minggo** [comment]
I think we should reconsider it in next version, so put it into `next`.

**Comment by ricardoquesada** [comment]
@minggo yes, thanks. I remember.

**Comment by minggo** [comment]
@ricardoquesada do you know the status of c++_static now? I would like to change to use c++_static too.

**Comment by ricardoquesada** [comment]
@minggo I'll take a look at it. as far as I know, the issue was the the Clang STL library... as far as I know c++_static is Ok to use it...
I got confused I guess in my previous answer... but I'll do more research.

**UPDATE**:
Here is all the info: https://developer.android.com/ndk/guides/cpp-support.html
And yes, `c++_static` includes STL support... and it is not stable.

> The NDK's libc++ is not stable. Not all the tests pass, and the test suite is not comprehensive. Some known issues are:
> - Using c++_shared on ARM can crash when an exception is thrown.
> - Support for wchar_t and the locale APIs is limited.
> 
> You should also make sure to check the "Known Issues" section of the changelog for the NDK release you are using.

So, yes, c++_static is not stable. perhaps we can use STLPort instead until it gets stable.

@zeyangl what issues in particular did you find in gnustl ? I want to try stlport and see if they are fixed there. thanks.

**Comment by mtak-** [comment]
In the older NDK's (<r11?) `gnustl` does not support basic things like `std::to_string` and is completely lacking in C++14 library features.

My two cents:
- `c++_static` does not have the exception issue, only `c++_shared` does (and it seems mostly fixed in r12)
- we've been using `c++_static` with cocos2d-x 3.9 and NDK (r10e) for a while now with only one issue
- the `steady_clock` in `libc++` wasn't actually monotonic even though `steady_clock::is_steady == true`(setting time back/forward a few hours in settings would break it).

I would love for `c++_static` to be the default for cocos, but it is still listed as unstable.

**Comment by minggo** [comment]
@mtak- thanks for your information. The only issue you met is `steady_clock`? 

@ricardoquesada  i think it is better if we can re-check the status of c++_static with google guys.

**Comment by mtak-** [comment]
@minggo So far yes.

The full story: We have yet to ship a game with cocos2d-x, but we've had a game in the works for around 6 months using cocos (so far its been great 👍 ). In our other games we have 20+ million active android users on games that all use `c++_static`. The `steady_clock` issue hit us hard with our leaderboards (lots of people cheating by setting their time back, or just finishing a game in a different time zone).

Also, before we were using `c++_static` we were using `c++_shared` and the exceptions issue is the reason we switched to `c++_static`.

One major drawback to `c++_static` is that you are restricted to just one shared library (see [this](http://gosuwachu.io/2016/04/09/android-ndk-bug/)).

Hope that helps.

**Comment by minggo** [comment]
@mtak- congratulations for your game, and thanks for the information, it is valuable.

**Comment by ricardoquesada** [comment]
@minggo basically what @mtak- said.
we should not use `c++_shared`. And there are other bugs there, but it is still unstable.
What the Google guys said was: "it is unstable, but most of the core functionality is implemented and works Ok, but other parts don't".

So, if we are going to use it, we should do a lot of testing. But the good thing is that we are not using lots of STL features so we shouldn't have issues (or major issues).
And we should report the bugs that we find to the NDK team.

**Comment by minggo** [comment]
After thinking more about it, i think we should not change to c++_static currently. We don't use too much STL features, but we can't make sure we will notuse more in future. In fact we are using more and more. And if one of the feature has bug, it may take much effect to find out it, and we have to switch to gnustl_static again.

**Comment by ricardoquesada** [comment]
@minggo yeah... what we need is automated tests so that they can detect crashes and weird behaviors.

**Comment by minggo** [comment]
@ricardoquesada yep, i add automated tests in v4 plan.

**Comment by ricardoquesada** [comment]
@minggo nice!!

**Comment by minggo** [comment]
@ricardoquesada please refer to #16169, it seems using clang+gnustl_static has some problem. After testing, we found gnustl_static+gcc and clang+stl_static doesn't have crash issue. We haven't found the real reason.

**Comment by ricardoquesada** [comment]
@minggo Ok. I'll add some info in that link.

**Comment by drelaptop** [comment]
since cocos2d-x 3.17, Android build tools have been changed into __c++\_static over clang__

related PR, https://github.com/cocos2d/cocos2d-x/pull/18470

close this out-of-date issues.
