### ISSUE TITLE
Run on Web error when using --advanced property

### ISSUE THREAD

**Issue by toanpv12345** [cocos2d/cocos2d-x#14215]
Hi Cocos team!
I'm using v3.8.1 for my project. When I compiled project with command:

```
cocos compile -p web -m release 
```

then project run on Browser ok.
But when I compile with command:

```
cocos compile -p web -m release --advanced
```

then run on Browser, it show error **Cannot found module parseuri when load project.json file.**
Thanks!

**Comment by pandamicro** [comment]
have you extended moduleConfig with a `parseuri` module ?

**Comment by toanpv12345** [comment]
I don't extended moduleConfig with a parseuri module!

**Comment by boons** [comment]
Hi,

I don't know if it will help you, but in your cocos2D-html5 dir, edit modulesConfig.json and at the bottom of the file replace 

``` javascript
"socketio" : [
    "external/socketio/socket.io.min.js"
],
```

with

``` javascript
"socketio" : [
    "external/socketio/socket.io.js"
],
```

It worked for me.

**Comment by toanpv12345** [comment]
Thank boons,
It worked for me too!

**Comment by pandamicro** [comment]
Ok, I was misleading by `Cannot found module parseuri when load project.json file.` error, it shouldn't print such message though, we don't have any module named `parseuri`.

The reason was socket.io 's min file don't support Closure Compiler advanced mode, advanced mode have some side effect while compiling, it may break your program, we can ensure all cocos code can pass advanced mode, but any third party code is out of control
