### ISSUE TITLE
cpp-tests crash at Scene 8 - 11 in Node:SpritePolygon

### ISSUE THREAD

**Issue by xiaofeng11** [cocos2d/cocos2d-x#15154]
@ricardoquesada Please take a look on this issue.

When onTouchMoved called, these test scene will crash. It occur on all platform. 

And when initSprites function in SpritePolygonTestNoCrash test case called, it will crash on Windows platform.

**Comment by minggo** [comment]
@ricardoquesada Do you think we should fix it in v3.11? I plan to release it on Apr.20.

**Comment by ricardoquesada** [comment]
yes.
I think the Autogeometry feature that we have is kind of broken. Not very useful. I think we should replace it with the one that comes with Chipmunk 7.
If you are asking me if I can fix it before April 20, then I don't know since I'm working on something else right now. I think this is a question for @linshun

**Comment by minggo** [comment]
Got it, then i think we can not include it in v3.11 since it is not a new bug brought in this version.

**Comment by linshun** [comment]
Sure, please take it in the later version.

**Comment by ricardoquesada** [comment]
@linshun are you still awake? I think it is 1:00am there. Have some sleep :)

**Comment by stammen** [comment]
@minggo  @ricardoquesada The bug is at line 674 of CCAutoPolyon.cpp. The return value ret is created on the stack and destroyed when the method goes out of scope. ret contains some pointers which are not correctly copied with the copy constructor. This is a bug for all platforms.

``` c++
PolygonInfo AutoPolygon::generateTriangles(const Rect& rect, const float& epsilon, const float& threshold)
{
    Rect realRect = getRealRect(rect);
    auto p = trace(realRect, threshold);
    p = reduce(p, realRect, epsilon);
    p = expand(p, realRect, epsilon);
    auto tri = triangulate(p);
    calculateUV(realRect, tri.verts, tri.vertCount);
    PolygonInfo ret; // HERE IS THE PROBLEM. 
    ret.triangles = tri;
    ret.filename = _filename;
    ret.rect = realRect;
    return ret;
}
```

**Comment by stammen** [comment]
@minggo  @ricardoquesada  The copy constructor for PolygonInfo is not correctly copying the TrianglesCommand data.

**Comment by minggo** [comment]
@stammen thanks for the information. I think we need to refactor the class.

**Comment by ricardoquesada** [comment]
@stammen thanks. yes, good finding.

@minggo 
short-term:we should review its code, and fix the obvious bugs (the ones spotted by stammen, and probably will find others too)
long-term: replace it with chipmunk auto-poly code

**Comment by minggo** [comment]
@ricardoquesada sounds good.

**Comment by ricardoquesada** [comment]
I couldn't find the bug in the copy constructor and/or the `operator=`... looks good to me, but it is obvious that there is a bug because it is crashing on windows.
Unfortunately, at the moment, I don't have a windows machine with me to test it. So I'm doing a code review of the whole `PolygonInfo` class, and I found that there are too many copies `PolygonInfo` instance making the code slower...

**UPDATE**:
Another thing... I think this code is buggy (from UIScale9Srpite.cpp):

``` c++
_scale9Image->getPolygonInfo().setTriangles(triangles);
```

`getPolygonInfo()` returns a copy of `PolygonInfo`, allocating memory for the indices and vertices, and copying the old ones into the new one. But the copy is never assigned to the `_scale9Image`...

**Comment by ricardoquesada** [comment]
@minggo can you try my patch on Windows? if it still crashes on windows, could you send me the stack trace? Thanks.

This is my patch: https://github.com/ricardoquesada/cocos2d-x/commit/9ad3db063503a2b1af97ce05c358c2e2fbb342e0

**Comment by minggo** [comment]
I will try it when i have time.

**Comment by stammen** [comment]
@ricardoquesada @minggo I will test the patch.

**Comment by minggo** [comment]
@stammen thanks.

**Comment by ricardoquesada** [comment]
@stammen thanks. I couldn't find the bug in the copy constructor, so I just cleaned a little bit the interfaces and added a few asserts. thanks!

**Comment by stammen** [comment]
@ricardoquesada @minggo I fixed the crash in PR https://github.com/ricardoquesada/cocos2d-x/pull/9.

@ricardoquesada Please review.

**Comment by ricardoquesada** [comment]
@stammen many thanks! PR looks good!

**Comment by ricardoquesada** [comment]
closed: https://github.com/cocos2d/cocos2d-x/pull/15722
