### ISSUE TITLE
Can't compile with NDK r11 for Android

### ISSUE THREAD

**Issue by ryukbk** [cocos2d/cocos2d-x#15309]
With NDK 11.1.2683735 (r11) which comes with Android Studio 2, building a project by "cocos compile" with --app-abi x86 fails by make errors that wrongly assumes it's toolchain 4.8 (4.9 is correct) and tries to find Android/sdk/ndk-bundle/toolchains/x86-4.8/prebuilt/darwin-x86_64/bin/x86-g++.

**Comment by 1scaR1** [comment]
Use --ndk-toolchain flag to specify Android Toolchain version(type full name, for example : arm-linux-androidabi-4.9)
It will solve your problem, but there is another one: it wouldn't compile because of some changes in r11 and you will get such error:
_Error:error: undefined reference to '__page_size'_

**Comment by dimbonix** [comment]
As an adhoc, in the root directory of ndk you can create file RELEASE.TXT and write to it text(without quotes): "r11b (64-bit)" or "r11b (32-bit)" depends on what version you are using. It works for me, but i dont know why ndk requires that file. I have found RELEASE.TXT file in previous ndk versions, but ndk11b doesnt contain it.

**Comment by minggo** [comment]
It is fixed with latest codes.
