### ISSUE TITLE
Android: Warning about -Wno-extern-c-compat

### ISSUE THREAD

**Issue by xpol** [cocos2d/cocos2d-x#15449]
Android flag `-Wno-extern-c-compat` added at:
- https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/Android.mk#L280
- https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/Android.mk#L282
- https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/Android.mk#L36
- https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/Android.mk#L38

cause a lot of warnings:

> cc1plus: warning: unrecognized command line option "-Wno-extern-c-compat"

Is `-Wno-extern-c-compat` an old flag for old compilers? Is it safe to remove it?

**Comment by minggo** [comment]
Fixed in #15509. These flags were used for clang, since we use gcc, so remove these flags.

**Comment by mars3142** [comment]
I saw a talk about NDK and in this talk they said, that clang is compiling faster (https://youtu.be/Ok97X9Z4Si8?t=1827) and since NDK r11 "GCC in the NDK is now deprecated in favor of Clang." (https://developer.android.com/ndk/downloads/revision_history.html). So it would be cool if in the future the NDK build could switch. Should I open a new bug?

**Comment by minggo** [comment]
@mars3142  There is already an issue #15577.
