### ISSUE TITLE
Sprite3D batching does not working.

### ISSUE THREAD

**Issue by IgorMats** [cocos2d/cocos2d-x#15877]
According to cocos2d::Renderer::processRenderCommand I can see that batchDraw method will be called in any condition so CC_INCREMENT_GL_DRAWN_BATCHES_AND_VERTICES will be increment too!

flush3D method is really calling only 1 time but only batchDraw will really draw the content.

Can you please help me with this?
Extremely grateful!

Forum link: http://discuss.cocos2d-x.org/t/performance-question-sprite3d-performance/29606

**Comment by ricardoquesada** [comment]
answered in the forum. Closing issues as batching in 3d never worked... in any case, it could be a feature request... and perhaps it could be implemented with instancing of something like that.

Reopen this one if you want this feature. Please add as more detail as possible since batching in 3d is not as common as in 2d.
