### ISSUE TITLE
WebSocket.cpp LOGD(..) using printf for logging but not console window is opened when starting game

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#15917]
in the code  the line #define  LOGD(...) printf(**VA_ARGS**) : 

```
#if COCOS2D_DEBUG > 0
    #ifdef ANDROID
        #define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG,__VA_ARGS__)
    #else
        #define  LOGD(...) printf(__VA_ARGS__)
    #endif
#else
    #define  LOGD(...)
#endif
```

is using printf for longing but it useless because i windows there is no console that is opened , all logs should go to : 

```
void CC_DLL log(const char * format, ...) CC_FORMAT_PRINTF(1, 2);
```

**Comment by minggo** [comment]
The log will in the VS debug output.

**Comment by meiry** [comment]
Hey minggo 
see in VC 213 , after i passing the DLOG i dont see any thing . 
as i know printf dont print to VS debug output
![dbug](https://cloud.githubusercontent.com/assets/1107316/16291935/fd4fc616-3914-11e6-8cfb-7bd141d6389d.png)

**Comment by minggo** [comment]
@meiry I agree with you. The codes in `WebSockets.cpp` says CCLOG is not thread safe, but i don't find it is not thread safe. So i think we should replace it with CCLOG.

**Comment by meiry** [comment]
Thanks how do i push fix ?

**Comment by minggo** [comment]
@meiry You are appreciated if you can send a PR to cocos2d-x.

**Comment by meiry** [comment]
no problem but how ?

**Comment by minggo** [comment]
You can do it when you have time, thanks.

**Comment by dumganhar** [comment]
Output log in visual studio was fixed.
Please refer to https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/WebSocket.cpp#L110

About the thread-safe problem, I think it's probably because invoking `Director::getInstance()->getConsole()->log(buf);` at the end of `cocos2d::log`.

Since the latest v3 branch has supported to output log in visual studio, I closed this issue.

If you still meet issues, feel free to re-open or create a new one.
