### ISSUE TITLE
gen-simulator&gen-templates need "ide-support"

### ISSUE THREAD

**Issue by SoBE-R-GL** [cocos2d/cocos2d-x#16083]
gen-simulator & gen-templates need "ide-support", but it has be removed?

**Comment by SoBE-R-GL** [comment]
and, when i add it from the old version, gen is also failed

**Comment by minggo** [comment]
@ricardoquesada do you know `gen-templates`? As i remember, it is used for cocos studio? And should we remove this command?

About `gen-simulator`, @slackmoehrle @natural-law do you know it? And even this command is needed, i don't think it need `ide-support` since code ide is not supported for a long time.

**Comment by minggo** [comment]
As discussed with @natural-law , we should fix it in cocos command.

**Comment by ricardoquesada** [comment]
@minggo no idea.. sorry. I've never used it.

**Comment by minggo** [comment]
@ricardoquesada @natural-law said he will fix it.
