### ISSUE TITLE
corrupt member variable in Node

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#16132]
As scene here: http://discuss.cocos2d-x.org/t/member-variable-is-corrupted-in-ios-but-works-fine-on-android/30835

**Comment by vyder** [comment]
*technically not in `Node`, but in a class that's derived from `Node`

**Comment by vyder** [comment]
Figured out the issue myself. The problem was in the way I was trying to subclass `Node`. If anyone can shed more light on the "why?" of the matter by comparing [my solution](http://discuss.cocos2d-x.org/t/member-variable-is-corrupted-in-ios-but-works-fine-on-android/30835/3) to my question, that would be awesome!

Thanks for your help @slackmoehrle!

**Comment by minggo** [comment]
@vyder you can not cast a Node to Hero of its real type is not Hero. That's the reason.
