### ISSUE TITLE
cocos commandline failed if iOS project has xcworkspace (because of pod)

### ISSUE THREAD

**Issue by mars3142** [cocos2d/cocos2d-x#16344]
- cocos2d-x version: 3.11.1
- developing environments
  - Xcode version: 7.3.1 (7D1014)

I have added pods to my project, so the project is moved from xcodeproj to xcworkspace. But after that, I can't compile the iOS project with the command "cocos compile -p ios", because it failed to find the pod library.

**Comment by cezheng** [comment]
Yep, that's the reason I use the prebuilt binaries of 3rd party SDKs instead of cocoapods.

Actually that might be better because cocoapods tend to generate lots of garbage and it constantly breaks backward compatibility. Also, it might even break or mess the build settings of cocos2d-x projects. Even for pure iOS apps I have switched to [Carthage](https://github.com/Carthage/Carthage), which is more flexible & you have full control of your project.

**Comment by minggo** [comment]
cocos command doesn't support pod, and we have no plan to support it
