### ISSUE TITLE
Spine: PolygonBatch flush cause crash

### ISSUE THREAD

**Issue by wulv1985** [cocos2d/cocos2d-x#16543]
- cocos2d-x version: 3.3
- devices test on: iphone6s plus
- developing environments
  - NDK version:
  - Xcode version: 7/8
  - VS version:
  - brower type and version:

Steps to Reproduce:
1. upgrade ios to ios10 beta7, app may crash when we use spine

i think there is a problem in function PolygonBatch::flush:

```
GL::bindVAO(0);
glEnableVertexAttribArray(GLProgram::VERTEX_ATTRIB_POSITION);
glEnableVertexAttribArray(GLProgram::VERTEX_ATTRIB_COLOR);
glEnableVertexAttribArray(GLProgram::VERTEX_ATTRIB_TEX_COORDS);
```

it should be replace by:

 GL::enableVertexAttribs(GL::VERTEX_ATTRIB_FLAG_POSITION | GL::VERTEX_ATTRIB_FLAG_COLOR | GL::VERTEX_ATTRIB_FLAG_TEX_COORD);

otherwise, the s_attributeFlags in GL:enableVertexAttribs will dismatch the real state

**Comment by jminht** [comment]
@wulv1985 where did you get the crash ?
is that in LayerColor::onDraw glDrawArrays(GLTRIANGLE_STRIP, 0, 4)?
how did you find out the problem in Spine: PolygonBatch?
i just find out may be the problem is something while remove spine.
could you share your way of solving the problem?

**Comment by wulv1985** [comment]
@jminht Yes! Exactly in LayerColor::onDraw glDrawArrays(GLTRIANGLE_STRIP, 0, 4) !

first, i found the crash is caused by reading invalid address by the crash infomation.

in LayerColor::onDraw, before glDrawArrays function , we will call glEnableVertexAttribArray and glVertexAttribPointer. i guess it's not match.

after print the VertexAttribArray status, i confirm that there is a problem!  The s_attributeFlags in GL:enableVertexAttribs is dismatch with the real status. 

then, i search the whole project where the glEnableVertexAttribArray/glVertexAttribPointer is called, then i find the polygonbatch set the status in a wrong way.  i log the last address used in polygonbatch for GLProgram::VERTEX_ATTRIB_TEX_COORDS, and it is exactly the address trying to read when crash!

**Comment by wulv1985** [comment]
@jminht hi, i finally solve the problem by the way i mentioned above.

**Comment by jminht** [comment]
@wulv1985 
Awsome!
I'll try what you mentioned above.
Thank you very much!

**Comment by jminht** [comment]
@wulv1985 Sorry, but i still have some problem.

> 1 after print the VertexAttribArray status

where to print the VertexAttribArray status?

> 2 The s_attributeFlags in GL:enableVertexAttribs is dismatch with the real status.

what do you mean by "real status"?

> 3 i search the whole project where the glEnableVertexAttribArray/glVertexAttribPointer is called

what's the rule to choose the result?
i searched the `glEnableVertexAttribArray` and i found it was called in `DrawNode/ParticleSystemQuad/Renderer/TextureAtlas`.
and i got more results while i searched `glVertexAttribPointer`.
With so many results, how could you finaly find out the problem is the calling in polygonbatch?
By reading the code? but how to identify the wrong calling?

> 4 then i find the polygonbatch set the status in a wrong way

what do you mean by 'set the status in a wrong way'?
Is it `glEnableVertexAttribArray(GLProgram::VERTEX_ATTRIB_TEX_COORDS);`?
why is it wrong?

> 5  i log the last address used in polygonbatch for GLProgram::VERTEX_ATTRIB_TEX_COORDS

how to log the address?
`printf("the address last used is 0x%x", &_vertices[0].texCoords);`

As you may see, i'm weak but curiouse about the debugging in GL issues.
Could you tell me more information about these steps ?
Hope this won't bother you.

**Comment by jminht** [comment]
@wulv1985 
the difference between the old and the new code is 
when i use `GL::enableVertexAttribs`, i just get one more step `glDisableVertexAttribArray(GLProgram::VERTEX_ATTRIB_NORMAL)`

is this the step which caused the crash?

**Comment by ArvinChen** [comment]
It solved the crash problem on ios 10, but on lower ios version, the spine animation will disappare.

**Comment by jminht** [comment]
@ArvinChen what do you mean by lower ios verion?
lower than ios7?

**Comment by ricardoquesada** [comment]
@jminht what cocos2d-x version are you using? could you test it with v3.13? thanks.

**Comment by wulv1985** [comment]
@jminht 
1.where to print the VertexAttribArray status?
i print status in GL:enableVertexAttribs function, after all the glxxx are done. using glGetVertexAttrib.

2.what do you mean by "real status"?
the real status is got by glGetVertexAttrib function, means which array index is enable/disable.  the var s_attributeFlags also keep this information, by they are not the same.

3.how to identify the wrong calling ?
i search "glEnableVertexAttribArray", and it shows about 30 matching lines. but, actually only in several functions!  i check the function one by one. i find only in polygon it calls GL::bindVAO(0), just like the GL:enableVertexAttribs do. others will gen vao and bind it.

4.what do you mean by 'set the status in a wrong way'?
the two ways both call glEnableVertexAttribArray correctly, but GL:enableVertexAttribs will also save the flags, and disable the useless attrib, if you don't do that, the next GL:enableVertexAttribs may call glEnableVertexAttribArray/glDisableVertexAttribArray wrongly because it base on the wrong saved flags.
but i am curiouse  why it's ok below ios 10 and also ok in android

5.how to log the address?
not the _vertices[0].texCoords, you should use glGetVertexAttribPointerv to get the address hold by opengl.

that's my opinion, if it is something wrong, please let me know~

**Comment by wulv1985** [comment]
@ArvinChen 
It solved the crash problem on ios 10, but on lower ios version, the spine animation will disappare.

hi, which ios version ?

**Comment by jminht** [comment]
@wulv1985 
i don't know how to use glGetVertexAttrib correctly.
could you make a example for me?
sorry about that.

**Comment by wulv1985** [comment]
@jminht https://www.opengl.org/sdk/docs/man2/xhtml/glGetVertexAttrib.xml

**Comment by jminht** [comment]
@wulv1985 
yeah, before i ask the question, i've googled for it.
actually, what i readed is https://www.opengl.org/sdk/docs/man4/html/glGetVertexAttrib.xhtml.
i just don't know which func to choose while there are 6 functions there.
glGetVertexAttribdv/glGetVertexAttribfv/glGetVertexAttribiv/glGetVertexAttribIiv/glGetVertexAttribIuiv/glGetVertexAttribLdv.

```
GLint cur_attrib_position;
glGetVertexAttribiv(GLProgram::VERTEX_ATTRIB_POSITION, GL_VERTEX_ATTRIB_ARRAY_ENABLED, (GLint *)&cur_attrib_position);
GLint cur_attrib_color;
glGetVertexAttribiv(GLProgram::VERTEX_ATTRIB_COLOR, GL_VERTEX_ATTRIB_ARRAY_ENABLED, (GLint *)&cur_attrib_color);
GLint cur_attrib_tex_coords;
glGetVertexAttribiv(GLProgram::VERTEX_ATTRIB_TEX_COORDS, GL_VERTEX_ATTRIB_ARRAY_ENABLED, (GLint *)&cur_attrib_tex_coords);
```

i tried this and i'm curiouse that which index should i check?
According to the context above in Layer::onDraw, i should only check the position and color.
because it called GL::enableVertexAttribs( GL::VERTEX_ATTRIB_FLAG_POSITION | GL::VERTEX_ATTRIB_FLAG_COLOR ); above
Or should i check all the index if it was enabled though there is only four indexs totally.

**Comment by jminht** [comment]
OK. after days of work, i finally get the answer.
let's review the process which i think someone could get help.

why can we fix the issue by change the code in **PolygonBatch.cpp** when we get crash in **Layer::onDraw**?

at first, we get crash at glDrawArrays(GLTRIANGLE_STRIP, 0, 4).
xcode show that it mush be reading some address which was released.
so we google for it `glDrawArrays(gl_triangle_strip, 0, 4) exc_bad_access`.

after that we should get `glDrawArrays will use the vertex indexs that were enabled`.
so what are  the indexs that **can be enabled?**
Lucky that there are only four index: a_position/a_color/a_texCoord/a_normal.
we can watch them to check which one was enabled and readed illegally.

so what's the tool to watch them? (i got stuck here for days due to the unfamiliarity of opengGL functions)
as you may see above, we can use `glGetVertexAttrib` and `glVertexAttribPointer` to do the thing.
for example, watch attrib position.

```
GLint cur_attrib_position;
glGetVertexAttribiv(GLProgram::VERTEX_ATTRIB_POSITION, GL_VERTEX_ATTRIB_ARRAY_ENABLED, (GLint *)&cur_attrib_position);
GLvoid* p_position;
glGetVertexAttribPointerv(GLProgram::VERTEX_ATTRIB_POSITION, GL_VERTEX_ATTRIB_ARRAY_POINTER, &p_position);
```

![2016-09-20 6 22 42](https://cloud.githubusercontent.com/assets/4132186/18668059/e2a23b54-7f65-11e6-9a43-6dd103da1eb3.png)

We add this log code before `glDrawArrays(GLTRIANGLE_STRIP, 0, 4)` and run the proj again.
We get crash as usual.
But we can check which index was enabled and released before reading illegally.
Yeah! It's the a_texCoord!

So we searched the whole proj to see where did the texcoord index was enabled with `GLProgram::VERTEX_ATTRIB_TEX_COORDS`.
We should find out that only in `PolygonBatch.cpp` was the index enabled.
`glEnableVertexAttribArray(GLProgram::VERTEX_ATTRIB_TEX_COORDS);`

So we figured out that we should disable that index before `glDrawArrays(GLTRIANGLE_STRIP, 0, 4)`.
Of course we can use `glDisableVertexAttribArray(GLProgram::VERTEX_ATTRIB_TEX_COORDS)`.
And it seems that cocos2d recommend to use `GL::enableVertexAttribs` to enable vertex attrib.
Because that func will store the old indexs of attrib to be enabled and will disable the useless attrib.

So we can change the code to

```
GL::enableVertexAttribs( GL::VERTEX_ATTRIB_FLAG_POSITION | GL::VERTEX_ATTRIB_FLAG_COLOR | GL::VERTEX_ATTRIB_FLAG_TEX_COORD);
```

In this way, we fix the crash issue.

But we can dig more.
Why it will crash only in iphone6s with ios10.
What i get is something about the gl info.
iphone6:  gl.version: OpenGL ES 2.0 Apple  A8 GPU - 95.16
iphone6s:gl.version: OpenGL ES 2.0 Metal - 33
Is that something strange with **Metal**?

**Comment by jminht** [comment]
@wulv1985 
Thank you very much!

**Comment by doersa** [comment]
@jminht 
i read your comment that reviews the process for solve the problem,it give me so many helps.From the review,i has learned a way to solve the problem of OpenGl,Thank you for your shared very much.

**Comment by jminht** [comment]
@ricardoquesada 
I'm using low version of cocos2dx. and i upgrade part of the code.
as you may know, it's too hard to upgrade the whole engine while you changed some code.
So i think it's hard for me to reproduce the issue in v3.13 even though you may fixed the issue already.
what's more, what i want to know is something independent of specific version.
And you can check them above. (1/2/3/4/5)
All i want to know isn't only how to solve the issue, but also the process to solve the problem, so that i can gain the ability to solve the other issue.
And i was stuck at some points such as 
- how to  track the vertexAttribArray status and address?
- how to set the status correctly while calling glEnableVertexAttribArray is a wrong way?

Thanks a lot for what you've done.
Wish to get more thinking process of solving issues so that we can learn by solving issues and not only be a man using your commits.

**Comment by ricardoquesada** [comment]
@jminht 
Yes, I understand that. But for us, it demands a lot of energy to test old versions. If the bug is present in the latest version, we will happily fix it. We just need a test case to reproduce it.
So, right now I can't give you an answer because I can't reproduce the bug using the latest version.

**Comment by wulv1985** [comment]
@jminht hi, your comment that reviews the process for solve the problem is good! I am poor in english, so i can't make it clear, sorry about that

**Comment by jminht** [comment]
@ricardoquesada 
Got it. I'll try to reproduce the issue i might meet in the future.
Thank you all the same.

@wulv1985 
Without you, i won't go anywhere for the issue.
Thank you very mush and wish to learn more from you.

**Comment by zxgats1986** [comment]
Great job! Thx for your ideas and solutions. it works for me

**Comment by wulv1985** [comment]
@zxgats1986 I am glad to  hear that

**Comment by babcca** [comment]
@wulv1985 @jminht You are the best!.

**Comment by lsc1414** [comment]
@wulv1985 @jminht Thanks!

**Comment by takesoon** [comment]
thankyou，it works

**Comment by drelaptop** [comment]
this issues should be closed, because it have been solved. @wulv1985 @jminht
