### ISSUE TITLE
Failed to find class DTiPhoneSimulatorSystemRoot at runtime

### ISSUE THREAD

**Issue by suroorwijdan** [cocos2d/cocos2d-x#17091]
- cocos2d-x version: cocos2d-x-3.13.1
- devices test on: running build on simulator ios
- developing environments
   - NDK version: android-ndk-r13b
   - Xcode version: Version 8.1 (8B62)
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.  cocos run -p ios
2. Build Succeeds but simulator doesn't open up and following is the out in the console Failed to find class DTiPhoneSimulatorSystemRoot at runtime.

**Comment by natural-law** [comment]
@suroorwijdan
The problem is solved is [this PR of cocos2d-console](https://github.com/cocos2d/cocos2d-console/pull/388). But I'm sorry that version 3.13.1 is not include the change.

So, maybe you can solve the problem by one of the two solutions:
1. Update the engine.
2. Apply the change in the cocos2d-console of your engine manually.

Sorry for the inconvenience!
