### ISSUE TITLE
cocos compile run -p android no longer works after Android SDK update

### ISSUE THREAD

**Issue by dmrdev** [cocos2d/cocos2d-x#17424]
Just updated Android SDK tools to the latest version 25.3.1 and now tools/android.bat no longer works, it reports:
```
The "android" command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use
tools\bin\sdkmanager.bat and tools\bin\avdmanager.bat
Error running command, return code: 1.
```

- cocos2d-x version: 3.14

Steps to Reproduce:

1. Update android SDK to the latest versions
2. Launch android app build `compile compile -p android` or ``compile run -p android``

**Comment by dmrdev** [comment]
Moreover even `compile compile -p android --android-studio` doesn't work because it also depends on `android.bat` utility.

**Comment by liketemple** [comment]
meet same problem.

**Comment by dumganhar** [comment]
@natural-law , please take a look at this issue. Thanks.

**Comment by dmrdev** [comment]
As a temporary solution I downloaded the previous version (25.2.3) of SDK tools from this page:
https://developer.android.com/studio/index.html (see the bottom of the page)
and then replaced tools folder in the Android sdk with the previous one.

**Comment by dmrdev** [comment]
Sorry, maybe I created an issue in a wrong repository because the same issue was already posted to the cocos2d-console repository almost two weeks ago:
https://github.com/cocos2d/cocos2d-console/issues/404

but unfortunately it is not fixed yet.

**Comment by natural-law** [comment]
Yep, I will fix the problem later.
Before that, you can rollback the version of Android SDK tools to avoid the problem. Sorry for the inconvenience!

**Comment by natural-law** [comment]
@dmrntpv How did you got the Android SDK tools 25.3.1? I just installed the latest version of Android Studio. But I can't update the Android SDK tools version to 25.3.1 (I tried it both on Mac & Windows):
![image](https://cloud.githubusercontent.com/assets/488169/23500752/0dbfbf2e-ff6c-11e6-842c-03859c6ebb51.png)

**Comment by dmrdev** [comment]
@natural-law, I just run update and chose to update to the latest versions of all suggested packages.

**Comment by dmrdev** [comment]
@natural-law, just checked again and this is something interesting, now it suggests to update not to 25.3.1, but to 25.2.5.

**Comment by dmrdev** [comment]
Just now I have updated the tools to 25.2.5 and Android Studio no longer suggests to upgrade it further.

Maybe they rolled back the update after so many complaints.

**Comment by dmrdev** [comment]
I don't have any special update settings (canary, beta etc). All my Android Studio update settings are set to default.

**Comment by natural-law** [comment]
> Maybe they rolled back the update after so many complaints.

Yep, maybe it is. So, i'll solve the problem once i can reproduce it. Thanks for your feedback!

**Comment by yjwong** [comment]
Got this issue 2 days ago. As an alternative for the time being, I switched to using Gradle and `externalNativeBuild` to accomplish my needs. It does bring other great benefits like full debugger support and reliable code-completion in Android Studio.

**Comment by dmrdev** [comment]
@yjwong, could you please describe how you did that? Does it work with JSB to copy the fresh versions of js-files to resources?

**Comment by Morozov-5F** [comment]
Not only cocos project experiencing this issue. Android SDK developers just removed a whole bunch of tools. There's a comment on how to make a temporary workaround: https://github.com/NativeScript/nativescript-cli/issues/2583#issuecomment-283712933

**Comment by dmrdev** [comment]
@natural-law, the new version (25.3.1) of SDK tools is available again via Android Studio updater tool. You can update now and try to fix the issue. Thank you!

**Comment by formatCvt** [comment]
Confirm bug. Downgrade to 25.2.3 helps.
Looks like the solution should be come from Google

**Comment by thorx2** [comment]
@formatCvt Unfortunately Google has completely dropped the standalone GUI manager, ergo "android", and has moved all command line SDK management to a new tool found here <SDK_ROOT>\tools\bin\ **sdkmanager**

Not sure if somehow pointing the build command to the new tool would work or not but I am currently in the midsts of trying it.

**Comment by formatCvt** [comment]
@gamer-11 Cocos (and other game engines) uses tool "android" for project actions (https://developer.android.com/studio/tools/help/android.html), not for sdk management.
And now we have no command line tool for this, maybe Google knows how to create/update project from command line since they removed android tool.

**Comment by yjwong** [comment]
@dmrntpv I wrote a post on Medium detailing how to use `externalNativeBuild` with cocos2d-x so it doesn't depend on the `cocos` command line tool. I'm not sure if it works with JSB though, but I would imagine a Gradle script could function as a replacement.

If anyone's interested: https://medium.com/@yjwong/using-externalnativebuild-with-cocos2d-x-f6a3c8eacfc8

**Comment by formatCvt** [comment]
`externalNativeBuild` also discussed here https://github.com/cocos2d/cocos2d-x/pull/15676

**Comment by natural-law** [comment]
Hello, everybody. I'm improving command `cocos compile` to support the externalNativeBuild in gradle. After that, I'll solve the problem caused by the Android SDK tools 25.3.x.

Thanks for all your feedback!

**Comment by myxrome** [comment]
Hi, could you plese share your fix?

**Comment by thorx2** [comment]
@formatCvt Forgive me if I am wrong. I understand that the command had various purposes(and that other game engines use them, well even the Unity projects are affected by this update). I was merely stating the reason for Google to drop the tool might be that they wanted people to use Android Studio for most of the development. From the link you have shared I get the sense that they have bundled the same via Studio, meaning for the time being the only way (that I know of) to create and manage an android project is via the IDE.
 
It would be super awesome if we could just open up the project in studio and have the ability to code and compile/deploy in the same environment as in iOS development in xcode.

**Comment by slackmoehrle** [comment]
@natural-law a user on the forums posted this: https://goo.gl/IlUvSp might be worth a look. He had success.

**Comment by formatCvt** [comment]
@gamer-11 no problem =) You can try open/code/compile/deploy/debug in studio (Android Studio 2.3) with patch from here https://github.com/cocos2d/cocos2d-x/pull/15676 
But we need console too, for continuous integration

**Comment by natural-law** [comment]
Hi, guys! In the latest code of cocos2d-console, I've solved the error when using Android SDK Tools 25.3.x.

As [the release note of Android SDK Tools 25.3.0](http://tools.android.com/recent/androidsdktoolsrevision2530feb2017) said, the ant scripts has been removed. So, **The Eclipse project will not be supported** with Android SDK Tools 25.3.x. 

Hope it's helpful!

**Comment by formatCvt** [comment]
Thanks!

**Comment by atsimerman** [comment]
How about cocos2d-x-3.13.1 and earlier ?

**Comment by minggo** [comment]
It is nothing about cocos2d-x version. It is about the tools version you used.

**Comment by jgod** [comment]
Replacing the tools works for me. Thanks guys 👍

**Comment by james-muldoon** [comment]
What version of the tools works? I've been trying to install cocos for the past 3 days using this guide http://cocos2d-x.org/docs/installation/Android-terminal/index.html but all the versions are out of date

**Comment by jgod** [comment]
@james-muldoon 25.2.3 works for me

**Comment by james-muldoon** [comment]
@jgod thanks for the reply. 
That's the version of tools that I have, but I'm still getting the message "The "android" command is deprecated" (shown in screenshot). 
Are you perhaps using a different SDK or NDK version to me? My NDK is r10c.
<img width="960" alt="2017-04-10" src="https://cloud.githubusercontent.com/assets/12402930/24848284/50c070be-1e09-11e7-94d6-10f73e95ff27.png">

**Comment by minggo** [comment]
@james-muldoon i think @natural-law has already answered it above. You should copy `tools` from old Android SDK because some tools are deleted in new Android SDK.

**Comment by james-muldoon** [comment]
Doing this just creates a different error for me. Do you download the SDK through Android Studio? Since downloading the command line tools now no longer includes the android SDK (further complicating following the given installation instructions) 
<img width="960" alt="2017-04-10 3" src="https://cloud.githubusercontent.com/assets/12402930/24857880/2c755e3a-1e2d-11e7-9fa5-32ee49d7423c.png">

**Comment by piotrros** [comment]
@mingoo I've updated cocos console, android sdk tools to the latest and I'm still getting:

**cocos gen-libs -p android --app-abi armeabi-v7a**

```
running: '/Users/piotr/Documents/pierdoly/cocos2d-x-3.14/tools/cocos2d-console/bin/cocos compile -s /Users/piotr/Documents/pierdoly/cocos2d-x-3.14/tools/simulator -p android --ndk-mode release --app-abi armeabi-v7a'

Building mode: debug
Using Eclipse project : /Users/piotr/Documents/pierdoly/cocos2d-x-3.14/tools/simulator/frameworks/runtime-src/proj.android
Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0.
Error running command, return code: 101.
```

**Comment by crazyhappygame** [comment]
I have the same issue. Latest cocos console, android sdk tools 
 

> Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0

**Comment by pulsarvault** [comment]
https://dl.google.com/android/repository/tools_r25.2.5-windows.zip
https://dl.google.com/android/repository/tools_r25.2.5-macosx.zip
https://dl.google.com/android/repository/tools_r25.2.5-linux.zip

rename tools folder, and extract and put tools folder from above depending on your OS.

**Comment by Kingurus** [comment]
I had the same problem. Thank you rohitchauhan365 for posting the fix.

**Comment by rohitchauhan365** [comment]
If you still have .apk compilation problem with the latest ndk and sdk, you need to add "#include <unistd.h>" in cocos/platform/android/jni/ProcessCpuTracker.cpp

#ifdef ANDROID
#include <jni.h>
#include <android/log.h>
#include <unistd.h>
.........................

**Comment by rohitchauhan365** [comment]
You can use the latest and greatest SDK and NDK with Cocos 3.15. I used the following steps on Ubuntu to get it working without the Ant and the Slow and Bulky Emulator and Android-Studio, using command-line Gradle.

Extract java-jdk, android-sdk, android-ndk, cocos to /opt, and copy gradle-4.0-bin.zip to /opt
------------------------------------------------------------------------------------------------
Download the new android-sdk command-line tools only (without the bulky Android-studio), extract and place the tools folder inside android-sdk folder, and then place android-sdk inside /opt/. 

Install Android SDK packages with these commands,
sdkmanager "build-tools;26.0.0" "platforms;android-26" 
sdkmanager --update
sdkmanager --list

*** Create repositories.cfg if there is an error on Windows ***

In your ~/.bashrc file
------------------------------------------------------------------------------------------------
export PATH="$PATH:/opt/java-jdk/bin:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/android-sdk/platform-tools:/opt/android-ndk:/opt/cocos/tools/cocos2d-console/bin:/opt/apache-ant/bin"

export JAVA_HOME=/opt/java-jdk
export ANT_ROOT=/opt/apache-ant
export ANDROID_SDK_ROOT=/opt/android-sdk
export NDK_ROOT=/opt/android-ndk

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/opt/cocos/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_X_ROOT for cocos2d-x
export COCOS_X_ROOT=/opt
export PATH=$COCOS_X_ROOT:$PATH

# Add environment variable COCOS_TEMPLATES_ROOT for cocos2d-x
export COCOS_TEMPLATES_ROOT=/opt/cocos/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH
--------------------------------------------------------------------------------------------

Run the command,
source ~/.bashrc

Enter /opt/cocos directory and run,
python setup.py
---------------------------------------------------------------------------------------------

In these 3 build.gradle files,

~/Projects/MyProject/frameworks/runtime-src/proj.android-studio/app/build.gradle,

~/Projects/MyProject/frameworks/cocos2d-x/cocos/platform/android/libcocos2dx

~/Projects/MyProject/frameworks/cocos2d-x/cocos/platform/android/libcocos2dx-with-controller

Change SDK versions to the latest ones, like this:

    compileSdkVersion 26
    buildToolsVersion "26.0.0"

and,

minSdkVersion 16
---------------------------------------------------------------------------------------------
In ~/Projects/MyProject/frameworks/runtime-src/proj.android-studio/gradle.properties,

PROP_TARGET_SDK_VERSION=26

gradle.properties also has the signing-information for release mode .apk
----------------------------------------------------------------------------------------------
In ~/Projects/MyProject/frameworks/runtime-src/proj.android-studio/gradle/wrapper/gradle-wrapper.properties, in order to save yourself the hell of downloading gradle on every build.

Linux,
distributionUrl=file\:/opt/gradle-4.0-bin.zip

Windows,
distributionUrl=file\:/d:/gradle-4.0-bin.zip 
----------------------------------------------------------------------------------------------
You need to add "#include <unistd.h>" in cocos/platform/android/jni/ProcessCpuTracker.cpp

#ifdef ANDROID
#include <jni.h>
#include <android/log.h>
#include <unistd.h>
----------------------------------------------------------------------------------------------
New Android/iOS Native-Project,
cocos new MyProject -l js -d ~/Projects

Run the Native .apk Project in Web Browser for Testing, (No need for the bulky Emulator and Android-studio for now :)
cd ~/Projects/MyProject 
cocos run -p web

Compile and run Native-Project,
cd ~/Projects/MyProject 

cocos compile -p android --android-studio (creates debug .apk for arm)
cocos compile -p android -m release --android-studio (creates release .apk for arm)

**Comment by er-bpradip** [comment]
I have an old project in cocos 3.13.x and I have now modified the game code. i am unable to compile this code for android devices. 
Is there any easy way to upgrade my code to cocos 3.15.x version and compile it. I have upgraded by copying cocos2d folder from new version 1.15.x to my existing project and I saw following error 


**Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 52.021 secs
Stopped 0 compiler daemon(s).
Error running command, return code: 1.**


I am new to cocos, any help will be highly appreciable.

**Comment by williamxhero** [comment]
cocos2dx is dead. if not for the legacy project, We will definite using Unity.

**Comment by v1993** [comment]
@minggo do you agree with @williamxhero?

**Comment by minggo** [comment]
No, it is caused by Android SDK issue. I think i answered it above. You can use `cocos run -p android --android-studio` or copy tools folder from old Android SDK.

**Comment by sgwood** [comment]
@minggo cocos run -p android --android-studio also failed. why?

**Comment by TankTheFrank** [comment]
@minggo Ant was deprecated a long time ago, unless you're time traveling from 2009 I would say is definitely not an Android SDK issue.

**Comment by minggo** [comment]
@sgwood `cocos run -p android --android-studio` works.
@TankTheFrank android command is also removed too. What this issue is saying that, Eclipse projects are not supported.

**Comment by lalaphoon** [comment]
@minggo if my old cocos project (created from 3.4) doesn't have proj.android-studio, is it okay to copy and paste from where it has one (like a project created in 3.16)?

**Comment by huhuang03** [comment]
In latest `android sdk`, the `android.bat` seems misssing. So functions depends on `android.bat` will fail, likes `projectRoot/setup.py` setup andorid.

There's no plan to fix this?
