### ISSUE TITLE
Running Liquid Action on NodeGrid changes appearance of nodes to a black hue/tint

### ISSUE THREAD

**Issue by codinghaven** [cocos2d/cocos2d-x#17536]
cocos2d-x v3.14
Iphone 5s, Samsung Tab E
- developing environments
   - NDK version: 11.2.2725575
   - 8.2.1
   - VS version: N/A
   - browser type and version: N/A

Steps to Reproduce:

1. Create NodeGrid
2. Create Liquid Action
3. add some Button images with transparency and with `setTouchEnabled()` to the node grid
4. run liquid action
5. add NodeGrid to a rendering layer 
6. run app and click on the last button you added
7. result = changes all other Buttons to black

**Comment by dumganhar** [comment]
Could you please upload the sample code for reproducing this issue? Thanks.

**Comment by codinghaven** [comment]
`auto liquid = Liquid::create(2, Size(15, 15), 3, 5);`
  `auto nodeGrid = NodeGrid::create();`
  `nodeGrid->runAction(RepeatForever::create(liquid));`
  `this->addChild(nodeGrid) // add nodeGrid to the layer`
  
  `auto b1 = Button::create("button.png")`
  `auto b2 = Button::create("button.png")`
  `auto b3 = Button::create("button.png")`
   
   `nodeGrid->addChild(b1);`
   `nodeGrid->addChild(b2);`
   `nodeGrid->addChild(b3);`

This is the code that you put in `init()` function in your `Layer` that is added to a `Scene`
The issue happens when one clicks on `b3` and you will see all the buttons turn blackish.

Here is the image that I use for `"button.png"`
![bubble](https://cloud.githubusercontent.com/assets/12215501/24026434/80079756-0a97-11e7-8997-71bbcb935b36.png)

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17577

The reason is that:

* Button is created without `selectedImage`, then engine will provide a default 2*2 white texture, and it is set to not alpha premultiplied, which cause the blend function to `{GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA}`
* when Button is clicked, `Button::onPressStateChangedToPressed()` is invoked, and `_buttonClickedRenderer->setVisible(true);` is set, which means _buttonClickedRenderer will be drawn.
* `Renderer::drawBatchedTriangles()` will invoke `Triangle::useMaterial()` for each triangle command, which will change the blend function.
* Last Button's `_buttonClickedRenderer` is drawn last, which will change the blend function to `{GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA}`.  That's why you can only see the wrong effect when clicking last Button(button3 in this example)

So there are two issues:

* `_buttonClickedRenderer` should not be drawn if `selectedImage` is not passed in
* the default texture provided by engine should be set to premultiplied

Change one of above will fix the issue. But i fixed them in the PR.

**Comment by codinghaven** [comment]
ok also the issue also applies when I schedule a function to be called every frame on a Sprite 
it also tints the whole node grid children to blackish? 
Is this the same root of the issue?

**Comment by minggo** [comment]
Sorry, i can't catch your idea. Did you say another issue?

**Comment by codinghaven** [comment]
Yes it's the same thing but the issue is happening through a different cause.
When I create a `Sprite` and I schedule a update function the moment I add that sprite as a child to node grid it also turns everything to blackish color.

**Comment by minggo** [comment]
I think it is a different issue. Could you please create a new issue for it? You are appreciated if you can provide some codes as this issue did.

**Comment by codinghaven** [comment]
Yep I checked it is Ill close this one though
