### ISSUE TITLE
ui::Button 和ui::ImageView设置九宫格区域不正常的问题

### ISSUE THREAD

**Issue by xiayangqun** [cocos2d/cocos2d-x#17654]
- cocos2d-x version:3.14.1
- devices test on:iphone6
重现场景，在创建一个ImageView并加载到屏幕上之后，点击一个按钮，更换这个ImageView的纹理，比如说从彩色的纹理换成黑白的纹理。会发现这个ImageView的九宫格拉伸出现了问题，是按照默认的九宫格区域拉伸的，而不是更换纹理之前的九宫格设定区域拉伸。
使用的是
ui::Button::loadTextures
ui::ImageVIew::loadTexture
这个两个api的进行纹理的更换。

**Comment by tiagomartines11** [comment]
That issue applies to several UI components which accept 9-slice sprites.

Whenever `loadTexture()` is called on a ImageView with 9-slice data, its `virtualRenderer` loses `_capInsets` data and the `_renderMode` variable is reset to `QUAD` instead of `SLICE9`.

This is an annoying behaviour introduced with the Sprite re-work on v3.14.

I also tried an alternative, using `getVirtualRenderer()->setSpriteFrame()` instead of `loadTexture()`, but `_contentSize`/`_stretchFactor` is reset in this case.

So since 3.14 it is impossible to replace a 9-slice texture in a Widget with 9-slice support while keeping its size/stretch/slices.

I'd like to see an official solution to this problem at some point :+1:

**Comment by minggo** [comment]
@xiayangqun could you please provide a test case to save our time? Thanks.

**Comment by tiagomartines11** [comment]
Here is a quick example:

```cpp
ImageView* sprite = ImageView::create("Assets/yellow.png");
sprite->setScale9Enabled(true);
sprite->setCapInsets(Rect(10, 10, 44, 44));
sprite->setContentSize(Size(400, 150));
sprite->setNormalizedPosition(Vec2(0.5, 0.2));
scene->addChild(sprite);
    
Button* button = Button::create("Assets/yellow.png");
button->setScale9Enabled(true);
button->setCapInsetsNormalRenderer(Rect(10, 10, 44, 44));
button->setContentSize(Size(400, 150));
button->setNormalizedPosition(Vec2(0.5, 0.5));
button->setTitleText("Press me");
button->addClickEventListener([sprite](Ref* button){
        ((Button*)button)->loadTextureNormal("Assets/red.png");
        sprite->loadTexture("Assets/red.png");
    });
scene->addChild(button);
```

If you press the button **two** times you see the texture is changed and the insets are lost (image gets stretched) both for ImageView and Button.
This didn't happen before 3.14 Sprite refactor.

Thank you for looking into this!

Images:
![red](https://cloud.githubusercontent.com/assets/2766836/25788379/fe0f2fd2-337e-11e7-89fe-c6816755219a.png)
![yellow](https://cloud.githubusercontent.com/assets/2766836/25788380/fe1170a8-337e-11e7-9b88-d2c145a21dc1.png)

**Comment by tiagomartines11** [comment]
Any updates on this issue? Thanks!

**Comment by renatoaf** [comment]
I'm experiencing the same problem. Has anyone else found a solution?
