### ISSUE TITLE
pauseEventListenersForTarget doesn't work correctly while in dispatching event

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17835]
- cocos2d-x version: v3.15
- devices test on: mac
- developing environments
   - NDK version: 
   - Xcode version: 8.3.2
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Create a MenuItemFont and a sprite and add them to scene
2. Create EventListenerTouchOneByOne in MenuItemFont's callback and addEventListenerWithSceneGraphPriority(listener, sprite), then pauseEventListenersTarget(sprite)
3. The sprite is still touchable.

Expected:
The sprite isn't touchable since the listener was paused by user's code.

**Comment by eryue** [comment]
@dumganhar 你好。
有这样的代码
`
widget:retain();
widget:removeFromParentAndCleanup(true);
parent:addChild(widget);
widget:release();
`
cleanup的时候加了removeEventListenersForTarget后，_touchListener被移除了，这个widget就无法触发点击事件了。

**Comment by summerinsects** [comment]
@eryue  用removeFromParentAndCleanup(false)，true的话会清理_touchListener

**Comment by kmaker** [comment]
@minggo @dumganhar 
Hi. I know this issue was closed a long time ago, but I think the solution adopted is not 100% correct. 
I have an EventListener which is added (using addEventListenerWithSceneGraphPriority) and removed from dispatcher according to external events. In certain cases, the listener is not properly unpaused by the engine.

Let's assume this order of events:
(1) onExit is called on the associated node (the listener gets paused)
(2) the listener is removed from dispatched
(3) onEnter is called on the associated node
(4) the listener is added again to dispatcher

The problem here is that the listener won't get unpaused on (4) because the code that resumed events on EventDispatcher::forceAddEventListener was removed.

I think the solution for this issue should have been this:

```
void EventDispatcher::forceAddEventListener(EventListener* listener)
{
	...
	if (node->isRunning()){
		resumeEventListenersForTarget(node);
	}
	else {
		listener->setPaused(true);
	}
	...
```

rather than:

```
	if (!node->isRunning()){
		listener->setPaused(true);
	}
```

removing the resumeEventListenersForTarget call. Why did you removed that line?
