### ISSUE TITLE
Cpp-test compiled failed in ProcessCpuTracker.cpp when using android studio 2.3.2 (cocos2d-x 3.15.1)

### ISSUE THREAD

**Issue by guoyingtao** [cocos2d/cocos2d-x#17940]
- cocos2d-x version: 3.15.1
- devices test on: Android simulator
- developing environments
   - NDK version: 15.0.4075724
   - Android studio: 2.3.2

Steps to Reproduce:

1. Import cpp-test
2. Compile

<img width="777" alt="qq20170617-123006 2x" src="https://user-images.githubusercontent.com/26723384/27254563-babfcfbc-5358-11e7-9f71-8b2d7a491f0d.png">

**Comment by Rubonnek** [comment]
I got the same error after updating the Android-related tools to version r26 in Arch Linux.

**Comment by Rubonnek** [comment]
Downgrading the NDK to r14b did the trick for me. I also downgraded all the other tools to r25.

**Comment by guoyingtao** [comment]
Thanks for your answer. I downgraded NDK to r14 and it compiled successfully, but when I start the app, it said: "Unfortunately, CppTests has stopped."

**Comment by guoyingtao** [comment]
It worked when I used my phone, but it still doesn't work on my simulator. Anyway, Thanks a lot! @Rubonnek

**Comment by Rubonnek** [comment]
@guoyingtao Anytime. The simulator issue has already been fixed in the pull request at #17901 and it was previously reported in #17850.

**Comment by guoyingtao** [comment]
@Rubonnek Thanks. Does it mean I have to wait for a new release of cocos2d-x, or I just clone the source code?

**Comment by Rubonnek** [comment]
@guoyingtao The patches for both of the issues you pointed out were not in released in cocos2d-x v3.15.1. Feel free to include the patches on your own if you need them, but eventually they get added in the official release if you'd rather wait.

@minggo Will the pull request #17901 be included in 3.16? I think #17943 should also be included in 3.16 after it's reviewed of course.

**Comment by minggo** [comment]
@Rubonnek yep, #17901 will be included in 3.16, and #17943 will be included too.
Thanks.

**Comment by Rubonnek** [comment]
@minggo Anytime. Thanks for the information.

**Comment by virgilcwylie** [comment]
Hello, I guess we can run on NDK 15 by commenting few lines in that file? As Android Studio isnt supporting downgrading of NDK in sdk manager. I will have to manually download older version else..

**Comment by rohitchauhan365** [comment]
You can use the latest and greatest SDK and NDK with Cocos 3.15. I used the following steps 2 days back on Ubuntu 16.04 to get it working without Ant and without slow-and-bulky Emulator and Android-Studio, using command-line Gradle.

Extract java-jdk, android-sdk, android-ndk, cocos to /opt, and copy gradle-4.0-bin.zip to /opt
--------------------------------------------------------------------------------------------------------------------------
Download the new android-sdk command-line tools only (without the bulky Android-studio), extract and place the tools folder inside android-sdk folder, and then place android-sdk inside /opt/. It should look like /opt/android-sdk/tools

Install Android SDK packages with these commands,
sdkmanager "build-tools;26.0.0" "platforms;android-26" 
sdkmanager --update
sdkmanager --list

*** Create repositories.cfg if there is an error on Windows ***

In your ~/.bashrc file
----------------------------------------------------------------------------------------------------------------------------
export PATH="$PATH:/opt/java-jdk/bin:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/android-sdk/platform-tools:/opt/android-ndk:/opt/cocos/tools/cocos2d-console/bin"

export JAVA_HOME=/opt/java-jdk
export ANDROID_SDK_ROOT=/opt/android-sdk
export NDK_ROOT=/opt/android-ndk

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/opt/cocos/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_X_ROOT for cocos2d-x
export COCOS_X_ROOT=/opt
export PATH=$COCOS_X_ROOT:$PATH

# Add environment variable COCOS_TEMPLATES_ROOT for cocos2d-x
export COCOS_TEMPLATES_ROOT=/opt/cocos/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH
------------------------------------------------------------------------------------------------------------------------

Run the command,
source ~/.bashrc

Enter /opt/cocos directory and run,
python setup.py
-----------------------------------------------------------------------------------------------------------------

In these 3 build.gradle files,

~/Projects/MyProject/frameworks/runtime-src/proj.android-studio/app/build.gradle,

~/Projects/MyProject/frameworks/cocos2d-x/cocos/platform/android/libcocos2dx

~/Projects/MyProject/frameworks/cocos2d-x/cocos/platform/android/libcocos2dx-with-controller

Change SDK versions to the latest ones, like this:

    compileSdkVersion 26
    buildToolsVersion "26.0.0"

and,

minSdkVersion 16
---------------------------------------------------------------------------------------------
In ~/Projects/MyProject/frameworks/runtime-src/proj.android-studio/gradle.properties,

PROP_TARGET_SDK_VERSION=26

gradle.properties also has the signing-information for release mode .apk
----------------------------------------------------------------------------------------------
In ~/Projects/MyProject/frameworks/runtime-src/proj.android-studio/gradle/wrapper/gradle-wrapper.properties, in order to save yourself the hell of downloading gradle on every build.

Linux,
distributionUrl=file\:/opt/gradle-4.0-bin.zip

Windows,
distributionUrl=file\:/d:/gradle-4.0-bin.zip 
----------------------------------------------------------------------------------------------
You need to add "#include <unistd.h>" in cocos/platform/android/jni/ProcessCpuTracker.cpp

#ifdef ANDROID
#include <jni.h>
#include <android/log.h>
#include <unistd.h>
----------------------------------------------------------------------------------------------
New Android Native-Project,
cocos new MyProject -l js -d ~/Projects

Run the Native .apk Project in Web Browser for Testing, (No need for the bulky Emulator and Android-studio for now :)
cd ~/Projects/MyProject 
cocos run -p web

Compile and run Native-Project,
cd ~/Projects/MyProject 

cocos compile -p android --android-studio (creates debug .apk for arm)
cocos compile -p android -m release --android-studio (creates release .apk for arm)
cocos compile -p android --android-studio --app-abi x86 (creates debug .apk for Intel x86 device and emulator)
cocos compile -p android -m release --android-studio --app-abi x86 (creates release .apk for Intel x86 device and emulator)
