### ISSUE TITLE
git submodule update --init fail

### ISSUE THREAD

**Issue by zip520123** [cocos2d/cocos2d-x#18078]
I try to build a iOS app.

I follow steps in the Git user attention.
1. git clone https://github.com/cocos2d/cocos2d-x.git, OK
2. python download-deps.py, OK
3. git submodule update --init, fail

fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out
github.com[1: 192.30.253.112]: errno=Operation timed out

![2017-07-17 3 21 31](https://user-images.githubusercontent.com/1498003/28258418-afcfe8ae-6b03-11e7-819a-50ca43a9d3bd.png)

**Comment by minggo** [comment]
may be there is some issue with github, you can try it later

**Comment by zip520123** [comment]
It still time out today. I will try it tomorrow.

**Comment by ezequielleonzybert** [comment]
It's happening the same to me
According to chatGPT we have to configure our git to use http protocol instead of git with this command:
git config --global url."https://github.com/".insteadOf git://github.com/
That changes the problem to:

C:\Users\Ezequiel\Documents\cocos2d-x>git submodule update --init
Cloning into 'C:/Users/Ezequiel/Documents/cocos2d-x/tests/cpp-tests/Resources/ccs-res'...
Cloning into 'C:/Users/Ezequiel/Documents/cocos2d-x/tools/bindings-generator'...
Cloning into 'C:/Users/Ezequiel/Documents/cocos2d-x/tools/cocos2d-console'...
fatal: could not get a repository handle for submodule 'tests/cpp-tests/Resources/ccs-res'
