### ISSUE TITLE
Vec2 (2D) MoveTo forces Z coordinate to 0

### ISSUE THREAD

**Issue by NinjaGah** [cocos2d/cocos2d-x#18158]
- cocos2d-x version: 3.13.1 (but same on latest)
- devices test on: Windows

In my opinion this is more of bad design than a bug. When you call MoveTo::create(Vec2()) it does not preserve z coordinate. It took me a long time to figure out why my 2D animations weren't ordering correctly when placed in a 3D environment.

Steps to Reproduce:

1. Create a BillBoard
2. Add a few 2D Sprites to a billboard, setup z coordinates for all of them
3. setPositionZ() for all sprites on the billboard
4. Call MoveTo::create(Vec2(x,y)) on a few sprites -> all moves to Z coordinate 0 (CCActionInterval.cpp around line 1253)

So you ask why not just use MoveTo::create(Vec3)? It becomes really inconvenience as every Vec2 would need to become Vec3(x,y, sprite->getPositionZ()) if you are just trying to move a sprite on the same x-y plane, otherwise the Z coordinate always goes to 0. This messes up the sprite draw orders as sprites in 3D environment is affected by z coordinate and not z-order. This makes MoveTo(Vec2()) pretty useless in 3D unless you don't manage z coordinate at all. So my suggestion is either do not allow MoveTo(Vec2()) on 3D parents or simply just preserve z coordinate when doing 2D MoveTo. I recommend the latter as it would not affect movements in 2D environment, yet still useful for 3D environments.

**Comment by minggo** [comment]
Yep, you are right. There are many things that if you using in 3d environments. Node is designed for 2d environment, then 3d is asked and need to use the same codes as 2d by help developers move to 3d. Then 2d and 3d mixed but can not make all things work perfect.

I don't want to modify the codes to make 3d happy, because it can not fix all issues. As you said, it is a design issue.
