### ISSUE TITLE
I can't build my cocos2d-x or cocos2d-x's project by Ubuntu 17.04.

### ISSUE THREAD

**Issue by erikaemma** [cocos2d/cocos2d-x#18177]
- cocos2d-x version: 3.15.1
- devices test on: Ubuntu 17.04 x64
- developing environments
   - NDK version: I do not know.
   - Xcode version: I do not know what it is.
   - VS version: I do not know what it is.
   - browser type and version: firefox, but I do not know the version, and I do not use browser.

Steps to Reproduce:

1. download cocos2d-x-3.15.1.zip and unzip to /opt
2. apt-get install gcc-4.9 g++-4.9
3. ./setup.py and source command
4. ./install-deps-linux.sh
6. cocos new MyGame -p com.erikaemma.mygame -l cpp -d ~/WorkSpace/test/cocos_test
7. cocos run -p linux

The errors:
`
[100%] Linking CXX executable bin/MyGame
lib/libcocos2dInternal.a(CCFontAtlas.cpp.o)：在函数‘cocos2d::FontAtlas::~FontAtlas()’中：
/home/erikaemma/WorkSpace/test/cocos_test/MyGame/cocos2d/cocos/2d/CCFontAtlas.cpp:120：对‘libiconv_close’未定义的引用
lib/libcocos2dInternal.a(CCFontAtlas.cpp.o)：在函数‘cocos2d::FontAtlas::conversionU32TOGB2312(std::basic_string<char32_t, std::char_traits<char32_t>, std::allocator<char32_t> > const&, std::unordered_map<unsigned int, unsigned int, std::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, unsigned int> > >&)’中：
/home/erikaemma/WorkSpace/test/cocos_test/MyGame/cocos2d/cocos/2d/CCFontAtlas.cpp:214：对‘libiconv_open’未定义的引用
/home/erikaemma/WorkSpace/test/cocos_test/MyGame/cocos2d/cocos/2d/CCFontAtlas.cpp:228：对‘libiconv’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/MyGame.dir/build.make:170: recipe for target 'bin/MyGame' failed
make[2]: *** [bin/MyGame] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/MyGame.dir/all' failed
make[1]: *** [CMakeFiles/MyGame.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
执行命令出错，返回值：2。
`
BUT MY ICONV VERSION IS 1.14!

If I try to build cocos2d-x by source code, the error will be:
`/usr/bin/ld: 最后的链结失败: 输出不可表示的节`
and like:
`relocation R_X86_64_32 against symbol `_ZN15CProfileManager4RootE' can not be used when making a shared object; recompile with -fPIC`

My GCC and G++ version have 6, 5.3.0 and 4.9.4. But no one can work.

PS: I have installed OpenBLAS. I didn't know wether is can make those wrong

I put my error on http://forum.cocos.com/t/ubuntu17-04-x64-cocos2d-x/50103 but no one help me.

**Comment by minggo** [comment]
sorry, we don't test on `Ubuntu 17.04 x64`, and we can not make sure of it

**Comment by cirosantilli** [comment]
also raised at: http://discuss.cocos2d-x.org/t/cocos2d-v3-out-of-the-box-build-hello-world-bullet-linker-error-ubuntu-16-10/39104

**Comment by cirosantilli** [comment]
I managed to make it work!

The problem seemed to be with the pre-built binaries for bullet present at: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/tree/15149f454f6cf30652ee3df35b3b7fac26c4da28/bullet/prebuilt/linux/64-bit so I compiled them from source again and replaced the pre-built ones (TODO: maybe you have to also apply https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/155 before rebuilding bullet)

```
git clone https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src
cd cocos2d-x-3rd-party-libs-src
git checkout 9304b64ba0bb701d6af46b5a94151f45fcd83d2a
./build.sh -p=linux --libs=bullet
cp -rv linux/bullet/prebuilt/x86_64/* /path/to/cocosd2x/external/bullet/prebuilt/linux/64-bit/
```

Cocos at a33f0dfa49d4b953872de9f6b153a026713df125

Then I also had to fix the an fmod problem: https://github.com/cocos2d/cocos2d-x/issues/15137#issuecomment-336243063 and then everything worked:

![screenshot from 2017-10-12 20-50-14](https://user-images.githubusercontent.com/1429315/31515984-ffb65c5c-af8e-11e7-9b7d-6f02af5e0afd.png)


I compiled the entire cocos wth gcc g++ 6.3 of Ubuntu 17.04, so I suspect that the problem was that the pre-built binaries were compiled with an old version of gcc which for some reason broke compatibility (TODO find out exactly why), possibly the ancient 4.9 that `install-deps-linux.sh` installs:

```
#sudo update-alternatives --remove-all gcc
#sudo update-alternatives --remove-all g++

#sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60
#sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 60
```

TODO: now make everything work with -DBUILD_SHARED_LIBS. Breaks at freetype, attempt to fix removing `--disable-shared` from `cocos2d-x-3rd-party-libs-src/contrib/src/main.mk`, but then get:

```
/usr/bin/ld: ../../lib/libcocos2dInternal.so.3.13: undefined reference to symbol 'inflateEnd'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

then patience ran out.
