### ISSUE TITLE
tableview里cell按钮点击事件的bug

### ISSUE THREAD

**Issue by Liaoer** [cocos2d/cocos2d-x#18423]
- cocos2d-x version: 3.16
- devices test on: all device
- developing environments
   - NDK version: 13b
   - Xcode version: 9
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 创建tableview
2. 添加自定义cell，cell是个button
3.按钮事件丢失
CCNode.cpp 中的cleanup方法中添加了 _eventDispatcher->removeEventListenersForTarget(this)；导致事件被删除。。

**Comment by RuningBun** [comment]
是不是tableview没有开启触摸监听。

2017年10月31日 22:59，"Mr.Liao" <notifications@github.com>写道：

**Comment by nieyanbing** [comment]
第1次没问题 第2次就会丢失了

**Comment by Liaoer** [comment]
不是。去掉源码CCNode.cpp 方法cleanup 中的 _eventDispatcher->removeEventListenersForTarget(this)； 这行就ok了，这个是后来加的，没测试好

**Comment by nieyanbing** [comment]
确实是，我没做具体测试，原来用C++写的代码升级到3.16后，如果是一个DialogLayer 创建后第1次点击事件是正常，关闭后再打开这个对话框的所有点击事件都会失效。
但是后来用LUA写的代码好像没出现这个问题

**Comment by dumganhar** [comment]
@Liaoer  Could you provide a test case for this issue?

**Comment by summerinsects** [comment]
将tableView源码里所有的`removeChild(cell, true)`改为`removeChild(cell, false)`，使之不再cleanup即可。
去掉Node::cleanup中的`_eventDispatcher->removeEventListenersForTarget(this)`是不妥的。当一个Node不在渲染树上时，不应该响应事件。

Modify `removeChild (cell, true)` to `removeChild (cell, false)` in whole tableView's source code, so that do not cleanup the cell when recycle it.
It is incorrect to removed `_eventDispatcher-> removeEventListenersForTarget (this)` in Node :: cleanup. A node should not respond any events when it is not in the render tree.

**Comment by dumganhar** [comment]
@summerinsects , yep, tableview re-uses cells, so its children should not be cleaned up.
I will submit a Pull Request for this bug.

**Comment by dumganhar** [comment]
@Liaoer , could you test what @summerinsects said?

**Comment by Liaoer** [comment]
@dumganhar @summerinsects  it works,thanks!

**Comment by G0561** [comment]
这个修复准备在那个版本上?

**Comment by drelaptop** [comment]
@G0561 `added this to the 3.17 milestone on Nov 8` 意思是 3.17 版本上
