### ISSUE TITLE
Why not using SocketRocket for iOS while cocos creator is using ?

### ISSUE THREAD

**Issue by JoHuang** [cocos2d/cocos2d-x#18610]
As title,

I see so many issues of libwebsocket in iOS platform.
Why not using SocketRocket for iOS while cocos creator is using ?

Thanks,
Jo

**Comment by minggo** [comment]
SocketRocket only support iOS, we need a cross platform lib. And now iOS and Android both not use libwebsocket by default. You can use it if needed. And you can use SocketRocket if needed too in your game.

**Comment by JoHuang** [comment]
https://github.com/cocos2d/cocos2d-x/issues/17326
in the thread, it seems SocketRocket is a good solution.
And cocos creator is using it.

What is the default websocket lib used on iOS and Android?

**Comment by minggo** [comment]
Oh, my fault, libwebsocket is used, libcurl is not used. If using SocketRocket on iOS, then is there any solution for Android?

**Comment by JoHuang** [comment]
We may follow the cocos creator solution.
What is the lib for Android in cocos creator?

I wanna use socket io in my game, but am afraid to use because of so many issues there and not solved for a long time.

**Comment by dumganhar** [comment]
> I wanna use socket io in my game, but am afraid to use because of so many issues there and not solved for a long time.

Yep, plz use `WebSocket` directly. SocketIO is not improved for a long time and there are lots of issues with it.

**Comment by dumganhar** [comment]
@JoHuang 

> We may follow the cocos creator solution.

Yep, Cocos creator solution is using https://github.com/facebook/SocketRocket .
The decision needs to be made and the task needs to be scheduled.

**Comment by JoHuang** [comment]
@dumganhar 
I'm not sure what you mean use Websocket directly.
I thought SocketIO module is protocol based-on Websocket lib.
And libwebsocket or SocketRocket are "Websocket" lib.
The issues mentioned in this repo seems to be "Websocket" lib issue?

My servers are node Socket.io servers (only use websocket protocol) , how can I only use websocket to communicate with my server?
I may need to use the "room" feature provided by Socket.io.
Thanks

**Comment by dumganhar** [comment]
The client side of socket.io implementation is based on websocket.
Currently, the native SocketIO still has some issues. For example, can't support binary format, can't also re-connect automatically like which on web.

> I may need to use the "room" feature provided by Socket.io.
It's possible to implement a simple `room` strategy base on WebSocket protocol.
But your service probably has to use `WebSocket` rather than SocketIO since they are different.
SocketIO is higher level abstraction.

**Comment by JoHuang** [comment]
Is fixing websocket / SocketIO a high priority job here?

**Comment by dumganhar** [comment]
@JoHuang , that needs to be decided by BOSS. I'm busying with Creator stuff and technical support.
@minggo , What's the priority of refactoring SocketIO module?
And also when will we take the implementation of WebSocket in Cocos Creator to Cocos2d-x?
Perhaps, @linshun should make a decision for this request which will also benefit for Cocos Creator since lots of developers complain about this module.

**Comment by minggo** [comment]
@dumganhar  I think you can put it in high priority when handle cocos2d-x issues.
