### ISSUE TITLE
Drawcall batching in iOS has no performance Improvement

### ISSUE THREAD

**Issue by huachangmiao** [cocos2d/cocos2d-x#18797]
- cocos2d-x version: 3.16
- devices test on: iphone6s
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

https://discuss.cocos2d-x.org/t/drawcall-batching-in-ios-has-no-performance-improvement/42445

**Comment by yuriilychak** [comment]
@huachangmiao You need to use [texture atlas](https://www.codeandweb.com/texturepacker/tutorials/animations-and-spritesheets-in-cocos2d-x). It is not iOS problem. If you use two sprites from two images they don't batch automatically, cause use different textures.

**Comment by huachangmiao** [comment]
@yuriilychak  The point is the fps is same when I make 1 dc and 5000 dc. 
so, What is the purpose of reducing dc?

**Comment by yuriilychak** [comment]
@huachangmiao What your mac requirements? If you test in emulator it will be low cause you need powerful (and very expensive) mac to test in emulator, cause XCode try to run iOS for test device with full requirements (That's why you have 22 fps). If you run it on real device you get 60 fps. In your case you need draw only two textures in 10000 polygons, and they are static (you don't move every sprite in every frame), but if you try to move them every frame and change their zOrder i think your fps will be lower in second case :) .

**Comment by huachangmiao** [comment]
@yuriilychak 
I just run this in iphone6s ( real device). And I don't change any value after created them.
![8544759c502360bcab11531e2574d46e](https://user-images.githubusercontent.com/26161671/39406972-c308ac24-4bf1-11e8-8a79-f29b741ec83c.png)
![f396a1520679d617a51a72083a5e939f](https://user-images.githubusercontent.com/26161671/39406973-c422df44-4bf1-11e8-9f31-7dede19c07bc.png)

**Comment by yuriilychak** [comment]
@huachangmiao Interesting. Can you run this in c++ project? I don't use lua binding only c++, and in my case all work fine.

**Comment by huachangmiao** [comment]
http://forum.cocos.com/t/drawcall-ios/59378

**Comment by drelaptop** [comment]
Since this issue have been discussed at Chinese forum http://forum.cocos.com/t/drawcall-ios/59378, and @minggo have made a reply. 

So I think this issue should be closed, reopen it disagree @huachangmiao
