### ISSUE TITLE
Cocos2dx failed with cmake when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [cocos2d/cocos2d-x#18838]
Hi All,

I tried to build cocos2d-x with Visual studio 2017 update2 on Windows Server 2016, but it failed with CMake. This issue can be reproduced from v3 revision e74e07b. Could you help have a look about this issue? Thanks in advance!

**Steps to Reproduce:**
1. git clone --recursive https://github.com/cocos2d/cocos2d-x.git D:\Cocos2dx\src
2. Open a VS 2017 command prompt and browse to D:\Cocos2dx
3. mkdir build_x86 && pushd build_x86
4. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src

**Actual result:**
The whole log file please see attachment.
[log_x86_cmake.log](https://github.com/cocos2d/cocos2d-x/files/2021951/log_x86_cmake.log)

**Comment by drelaptop** [comment]
it's a issue, caused by https://github.com/cocos2d/cocos2d-x/pull/18816

you can revert it for a temp solution. I don't know why `configure_file(<input> <output> COPYONLY)` works well on macOS, but bad on windows, this should be research. @v1993 

Or using the cocos2d-x 3.17 tag, it's well tested. https://github.com/cocos2d/cocos2d-x/tree/cocos2d-x-3.17

**Comment by v1993** [comment]
@drelaptop I found this: https://cmake.org/pipermail/cmake/2006-March/008702.html

Look like cmake don't understand backward slash.

**Comment by drelaptop** [comment]
@shanshan0309 fixed here, I have tested using tests project, could you test it again?

after I research, I think the reason is the value of  `$<CONFIG>` isn't visible when execute `configure_file`.

**Comment by shanshan0309** [comment]
Thank you @drelaptop. It works well when I tried your fix.
