### ISSUE TITLE
Android template project doesn't build on `PROP_BUILD_TYPE=ndk-build`

### ISSUE THREAD

**Issue by pyrosphere** [cocos2d/cocos2d-x#19049]
The Android template project, created from `cocos new` fails to build if `PROP_BUILD_TYPE` is changed to `ndk-build`.

The error it throws is `Android NDK: Module MyGame_shared depends on undefined modules: uv_static` probably from pull request #19015

**Comment by v1993** [comment]
Question: do we still need ndk-build support on new projects? CMake seem much better at all (almost no separate build configuration, at least for files and flags) and works just fine.

**Comment by pyrosphere** [comment]
New projects should probably use CMake, but this breaks old projects that already use `ndk-build`.

**Comment by v1993** [comment]
> old projects that already use `ndk-build`.

> The Android template project, created from `cocos new`

I didn't get this.

P.S.: we should do one of things: fix it or remove `ndk-build` support at all (as not working).

**Comment by pyrosphere** [comment]
Every project using `ndk-build` is broken - the option is broken, but to open an issue I wasn't going to submit "my project is broken", I tested it using the template and confirmed it wasn't from any of my own custom configurations.

But yes, either `ndk-build` should be fixed or support removed.

**Comment by v1993** [comment]
Ok, get it now. Now just wait cocos team response.

**Comment by drelaptop** [comment]
It's a error on Android.mk, to fix this issue all you need to do is add this line

https://github.com/cocos2d/cocos2d-x/blob/46ba24f585a16a2a01eb6399f85e345d58c96e0a/cocos/Android.mk#L340

also rembmer to update external libs.

---
I think the reason is all the CI change the build type to cmake, so this `ndk-build` error didn't been found. we should add a `ndk-build` task at least. I will do it. 

this issue have been solved at https://github.com/cocos2d/cocos2d-x/pull/19045 (`ndk-build` CI passed, Not merged)

---
>Question: do we still need ndk-build support on new projects? 

keep `ndk-build` supported on v3 branch will perform a  good compatibility, we should do that

**Comment by crazyhappygame** [comment]
@drelaptop I do not insist but I think that we should not support ndk-build 
https://developer.android.com/ndk/guides/
`Android Studio's default build tool to compile native libraries is CMake. Android Studio also supports ndk-build due to the large number of existing projects that use the build toolkit. However, if you are creating a new native library, you should use CMake.`
I think that for new Android projects CMake should be used.
Support both cmake and ndk-build will be only source of problems like that one: " if PROP_BUILD_TYPE is changed to ndk-build/cmake"
Or something work on cmake/ndk-build does not work ndk-build/cmake ....

**Comment by drelaptop** [comment]
thanks for this advice, I hope so, but we can't do this on v3 branch. it will trouble developers when he upgrade engine release from 3.15 to 3.18. 

as google explained, `large number of existing projects that use the build toolkit`, cocos2d-x projects are same with that. We have changed the default build-type to cmake, that means we hope developers to use cmake for new project.

**Comment by drelaptop** [comment]
#19045 merged, remember to execute `download-deps.py` to update external.
