### ISSUE TITLE
(iOS) Improper Action with CCEditbox

### ISSUE THREAD

**Issue by CodeSnooker** [cocos2d/cocos2d-x#1971]
Hi James

@dumganhar 

Cocos2d-x Version: cocos2d-2.1beta3-x-2.1.0

Steps to reproduce issue:
1. Create a Scene.
2. Add a full screen size layer to the scene.
3. Add a CCEditbox to layer and put some text to it.
4. Add a CCMenuItem to layer and set actions to move layer to some point.
5. Click on Menu Item to initiate the move action of layer.

Result:

Only the background of the CCEditbox has moved but the text is there at the same place.

Another test
1. Hide the CCEditbox.
2. Click on the area where the CCEditbox was added.

Result:
1. Text is still visible even after hiding the box.
2. Keyboard will pop up on touch the area where CCEditbox was added.

Note: The issue is reproducible on iOS platform only.

**Comment by CodeSnooker** [comment]
@dumganhar  any update on this?

**Comment by dumganhar** [comment]
Hi, @CodeSnooker 
I sent a Pull Request to resolve some issues of CCEditBox here(https://github.com/cocos2d/cocos2d-x/pull/2045/files).
I think it will work with some actions that changing the postion of CCEditBox or its parent's layer.
Because it called `setPosition` in CCEditBoxImplIOS::visit.
But other actions like rotate and scale will not work.
