### ISSUE TITLE
CCEditBox problem of new version

### ISSUE THREAD

**Issue by ucchen** [cocos2d/cocos2d-x#2314]
Sorry, i am not good at english. with the new version cocos2d-x.when i use CCEditBox to create three input area just like a sample. when i touch first CCEditBox the keyboard will show and when i touch the second CCEditBox the keyboard will hide. in cocos2d-x 2.1.1 when i touche second CCEditBox, the keyboard will not hide and it will fouce on the second CCEditBox. And my question is why this function in new version doesn't work. thx

**Comment by dumganhar** [comment]
Hi @ucchen 
It's because we have refactored the implementation of CCEditBox for iOS.
You could refer to this Pull Request https://github.com/cocos2d/cocos2d-x/pull/2144.

## Why 2.1.1 works when touch the second editbox:

It's because we place three transparent system controls -- UITextField. So when you touch the second editbox, the touch event will directly pass to the second editbox. Therefore, keyboard will not be hidden.

## Why 2.1.2 will hide keyboard:

Normally, when no input is triggered, all system control will be hidden. 
When the first editbox is in focus state, the second and the third editbox are still in hidden status.
So when touch into the area of the second editbox, in fact, UITextField will not be active. 
That's why the keyboard is hidden immediately.

**Comment by ucchen** [comment]
how to achieve what i want , thx

**Comment by dumganhar** [comment]
@ucchen
Please use the implementation of CCEditBox in 2.1.1.

**Comment by tiantian20007** [comment]
I came across this issue too. Obviously, the best user experience is that when we touch the second input field, the keyboard will not hide, and the second input field will get focus on;

**Comment by dumganhar** [comment]
IMO, it's hard to achieve that. Do you have some ideas?

**Comment by jmgomezg** [comment]
Hi, sorry but I am having the same issue, when we have more than one input box it is a bit annoying you need to close and reopen the keyboard. I understand there may be problems, so what I did was to implement CCEditBoxDelegate on my layer, and on editBoxReturn try to open manually the next input. So on CCEditBox I created a public function to call:

m_pEditBoxImpl->openKeyboard();

It does work, but the input seems not to get the focus and typing has no effect. So if we could get a public method on CCEditBox that we can call manually to properly open the input and keyboard, would be brilliant and we could manage perfectly the multiple input boxes. I'm pretty new to cocos2d-x so my knowledge is limited.

Unless someone else has already found a better solution?

Thanks.

**Comment by godyZ** [comment]
@ucchen Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August.
