### ISSUE TITLE
CCLabelBMFont crash on glDrawElements in CCTextureAtlas::drawNumberOfQuads sometimes

### ISSUE THREAD

**Issue by tiantian20007** [cocos2d/cocos2d-x#2354]
It does not happen every time, however It never happen before I upgrade to 2.1.2.

**Comment by dumganhar** [comment]
Which platform?
Does `TestCpp/LabelTest` which uses CCLabelBMFont also crash sometimes?

**Comment by tiantian20007** [comment]
Sorry I forgot to add detail info: xcdoe 4.6.1 crash on simultor 6.1 and device: 6.1.3 & 4.3.3.
TestCpp/LabelTest works fine;

**Comment by dumganhar** [comment]
Could you provide a demo to reproduce this issue and send it to me?

**Comment by tiantian20007** [comment]
OK, I'll do it later.

**Comment by tiantian20007** [comment]
It's hard to reproduce this issue, but it happens sometime.
It crashed at line:631 of CCTextureAtlas.cpp, it's an openGL call "glDrawElements" in CCTextureAtlas::drawNumberOfQuads when a CCLabelBMFont::draw is invoked:

``` c++
glDrawElements(GL_TRIANGLES, (GLsizei) n*6, GL_UNSIGNED_SHORT, (GLvoid*) (start*6*sizeof(m_pIndices[0])) );
```

I looked into m_pIndices, and I found  only one element:  *m_pIndices GLushort 0
It looks like an empty array
May that be the reason for crash?

XCode gave the info: EXC_BAD_ACCESS (code=2, address=0x0)

**Comment by dumganhar** [comment]
Do you mean `m_pIndices` is NULL or the value of `m_pIndices` (i means m_pIndices[0]) is 0?

**Comment by tiantian20007** [comment]
m_pIndices is not NULL. 
But m_pIndices[0] is 0.

**Comment by tiantian20007** [comment]
![tmp4996898b](https://f.cloud.github.com/assets/406098/412468/3f130052-abb7-11e2-8d91-f66d38064954.png)

**Comment by dumganhar** [comment]
So have you found the way to reproduce this issue?

**Comment by tiantian20007** [comment]
No, I just record the stack trace when it happened;

**Comment by djciego** [comment]
I've found the same error. In my case it happens when I do the following:

//Create a label and add it
CCLabelBMFont *label1 = CCLabelBMFont::create("test", "someFont1.fnt");
this->addChild(label1);

// Remove this label
label1->removeFromParentAndCleanup(true);

// Create a new label and add it (then crashes)
CCLabelBMFont *label2 = CCLabelBMFont::create("test 2", "someFont2.fnt");
this->addChild(label2);

The fact is, if I don't remove label1 from parent, there's no problem. Both fonts are different, they are different labels...

Have you found any solution?

**Comment by ghost** [comment]
Can confirm it's about CCLabelBMFont and addChild() and removeChild() in a loop - or when it done often in game loop. Even V2.1.1 has this bug which yields to OpenGL  "glDrawElements" exception.

**Comment by tiantian20007** [comment]
I never found this again after upgraded to 2.1.3.

**Comment by ghost** [comment]
Even V2.1.3 has this bug which I can reproduce in a second in my app. I add and remove CCLabelBMFont  very often in a game. _CRASH_ after 1-10 sec. Now I don't remove it, just setVisibile(0/1) it does not crash!
All my sprites are on a batch node, except this label

**Comment by tiantian20007** [comment]
Ok, issue reopen;

**Comment by jllust** [comment]
Issue reproducible in 2.1.4 Would love to find a solution.
https://github.com/jllust/cocos2d-x/commit/41000c0e51620f89218cf89b9cf061bf3e52856b

This is happening after a CCLabelBMFont deallocs and glDeleteVertexArrays, then shortly after a Spine class with TextureAtlas allocs and glGenVertexArrays the same m_uVAOname. Then EXE_BAD_ACCESS code=2 on glDrawElements.

In my commit I've used the controller.cpp to quickly jump into creating BMFontVAOLayer and fore go the menu. This is mostly because this issue could be missed if too many VAO generate come and go, and using Spine will not overlap with a recently free VAO. This test will only generate up to 4 new VAO and SpineBoy will reuse the 4th.
If in LevelSelect the CCLabelBMFont totalLbl is not created, or is extra retained, SpineBoy will then generate VAO 5 and all is fine (assumingly until something else uses VAO 4 after the label is later released)

Fix:
So I'm not sure if this is the best solution, someone can review. I simply think that when GLStateCache is enabled, the VAO needs to be rebound, or simpler the cache needs to reset the recent vaoId. Directly after a glDeleteVertexArrays.
#if CC_TEXTURE_ATLAS_USE_VAO
    glDeleteVertexArrays(1, &m_uVAOname);
    ccGLBindVAO(0);

**Comment by tiantian20007** [comment]
Crash is gone after add ccGLBindVAO(0);
You should send a pull request.
Thx a lot, this problem used to bother me a lot.

**Comment by jllust** [comment]
Done PR #3144

**Comment by 52914001** [comment]
thx.

**Comment by dumganhar** [comment]
@jllust 
Thanks.

**Comment by jongrall** [comment]
This issue was driving me nuts. It affects cocos2d-iphone also. Thanks for the fix! Please bring this to the attention of the cocos2d-iphone maintainers (I will do so too).
