### ISSUE TITLE
Screen turns black if you press the home button while playing the game, and reopen it again

### ISSUE THREAD

**Issue by plungeint** [cocos2d/cocos2d-x#3029]
At least in samsung galaxy S2 (I9100) and S3 (I9300), open the game, press on the home button of the device (make sure there are several apps running in the background), reopen the app. Screen becomes totally black.

Very simple example (hello world example that adds 3 big sprites to the hierarchy).
https://www.dropbox.com/s/aaq8i5haow45h7r/test.zip

**Comment by folecr** [comment]
I took the liberty of updating the source code here and modifying the test slightly.
https://github.com/folecr/CocosBGFGTest

**Comment by folecr** [comment]
This bug is reproducible in the x86 emulator too and should be reproducible on other devices too
To reproduce
- Turn on Android Developer Options
  - device specific https://www.google.com/search?q=turn+on+Android+developer+options
- Enable `Don't Keep Activities`
  - Settings->Developer Options->Don't Keep Activities.

**Comment by zcgit** [comment]
so , what is the correct solution?

**Comment by minggo** [comment]
@plungeint 
Did you revert the modification of http://www.cocos2d-x.org/issues/1613 and have a try?

@folecr 
Have you tested on real phone?

**Comment by jhurt** [comment]
@minggo I was having the same problem on Kindle when upgrading from 2.1.2 to 2.1.4, reverting http://www.cocos2d-x.org/issues/1613 worked for me: https://github.com/jhurt/cocos2d-x/commit/16caffb60b4b47381d7646cf60fb684293f55c5a

**Comment by folecr** [comment]
> Have you tested on real phone?

Yes. Nexus 4.
To clarify : the bug is reproducible on real ARM devices and the x86 emulator.

**Comment by minggo** [comment]
@jhurt
Did you run many app in background as @plungeint did?

@folecr 
May be OpenGL context is released when the app in background and memory is limited. 
Does Android trig a callback when memory is limited as iPhone did?
If so, i think we should kill the app when memory is limited.

**Comment by folecr** [comment]
@minggo @zcgit 

This is the method called when the GL surface is created/recreated.
http://developer.android.com/reference/android/opengl/GLSurfaceView.Renderer.html#onSurfaceCreated(javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.egl.EGLConfig)

We should recreate OpenGL resources in this callback.
We should also check if the thread is being killed and a new thread is created on coming back to foreground.

**Comment by minggo** [comment]
@folecr 
Re-create OpenGL resources will take a long time, and it will make things complex:
- you should record every resources include shader, all OpenGL status

So i modified it to not to re-create all OpenGL context.
And this method works well with FishingJoy game, which has more than 100 billions downloads.

Now we met this issue, i think it is because the app in background, and system is out of memory, then the app resources will be reclaimed by system. But the app is not killed.

I don't think re-create all OpenGL context in this situation is a good idea.
I think we should exit app when system is out of memory.
Then system will re-start app again when reopen it.

What's your opinion?

**Comment by plungeint** [comment]
at any case killing the app is far better than a black screen from the user experience prespective

**Comment by jhurt** [comment]
@minggo I was getting the black screen on the Kindle fire 1st generation anytime onPause then onResume was called, even when my app was the only app running.

**Comment by minggo** [comment]
@jhurt 
Could you please revert the modification of http://www.cocos2d-x.org/issues/1613 and have a try?

Thanks.

@plungeint 
I agree with you.

**Comment by jhurt** [comment]
@minggo For clarification, I did revert http://www.cocos2d-x.org/issues/1613 and that fixed the issue. The link I posted earlier was the commit on my fork that reverted 1613.

**Comment by minggo** [comment]
@jhurt 
Your commit just change macro to 1, but not reverting all the change of http://www.cocos2d-x.org/issues/1613.
Though it cached data, but i didn't re-load all resources at all.

**Comment by plungeint** [comment]
Hi guys, is this issue in the roadmap? Until it is fixed what we could do to apply on released games? I think it's a critical issue.

Thanks!

**Comment by minggo** [comment]
There is a pull request #3117 for this issue.
I am not sure if it is correct or not.
Could any body helps to review it or test it?

Thanks.

**Comment by harikrishnar** [comment]
which is a better way to do?? the above PR or this? https://github.com/cocos2d/cocos2d-x/issues/2658

**Comment by minggo** [comment]
#2658 is a different issue.

**Comment by harikrishnar** [comment]
No #2658 fixed this issue for me :) and also when we press the lock button and come back to the app..
