### ISSUE TITLE
CCGLProgram crashed on some Android devices

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8157]
Some developers reported that, `CCGLProgram` will cause crash on some Android devices:
- crashed on GalaxyNexus report: http://discuss.cocos2d-x.org/t/ccglprogramcache-fatal-error/17220/3
- crashed on Kindle Fire report: http://discuss.cocos2d-x.org/t/cocos2d-x-v3-3alpha0-released/16586/68

And there is not problem in v3.2.

**Comment by minggo** [comment]
This issue is urgent.

**Comment by hamburml** [comment]
Hi. I am not sure if this may be the cause, but a developer from us tried v3.3beta and it crashed. He mentioned to me that  GLContextAttrs glContextAttrs = {8, 8, 8, 8, 24, 8}; (in AppDelegate.cpp) could be the problem, because of http://en.wikibooks.org/wiki/OpenGL_Programming/Stencil_buffer#Limitations DEPTH24_STENCIL8 is not supported. Haven't had time to look myself.

**Comment by minggo** [comment]
@Michael-Hamburger 
Thanks for your feedback.

We will comment it by default if we confirm it.

**Comment by minggo** [comment]
@Michael-Hamburger 
We created #8160 for it.
Thanks.
