### ISSUE TITLE
Specific picture drawn with "ping-pong" CCRenderTexture(s) “drifts” after each time of rendering

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8277]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3365). It was created at 2013/12/09 08:56:48 +0000
# Description

Found the problem while working on an shader program for some special effects. The original image was drawn to one CCRenderTexture renderTexture0 and then the content of renderTexture0 was drawn into renderTexture1. And then draw back from renderTexture1 to renderTexture0, and over and over again…, just like a ping-pong buffer.
It is expected that the final content of renderTextureX should be the same with original image, but actually it makes some offset from the original image.What stranger, is that it seems to happen only on some specific picture(s), while most other pictures are OK.

The source code is reduced to an useless but enough-to-show-issue version, using only cocos2d-x build-in shader programs. And the picture with problem is also posted below.

```
bool HelloWorld::init()
{
    //////////////////////////////
    // 1. super init first
    if ( !CCLayer::init() )
    {
        return false;
    }

    /////////////////////////////
    CCSize winSize = CCDirector::sharedDirector()->getWinSize();
    CCTexture2D* sourceImage = CCTextureCache::sharedTextureCache()->addImage("http://www.cocos2d-x.org/attatchments/3103/");
    CCSize size = sourceImage->getContentSize();
    CCRenderTexture* renderTexture0 = CCRenderTexture::create(size.width, size.height);
    CCRenderTexture* renderTexture1 = CCRenderTexture::create(size.width, size.height);

    renderTexture0->beginWithClear(0, 0, 0, 0);
    sourceImage->drawAtPoint(CCPointZero);
    renderTexture0->end();

    for (int i=0; i<100; i++)
    {
        renderTexture1->beginWithClear(0, 0, 0, 0);
        renderTexture0->getSprite()->getTexture()->drawAtPoint(ccp(0, 0));
        renderTexture1->end();

        renderTexture0->beginWithClear(0, 0, 0, 0);
        renderTexture1->getSprite()->getTexture()->drawAtPoint(ccp(0, 0));
        renderTexture0->end();
    }

    renderTexture0->setPosition(ccp(winSize.width/2, winSize.height/2));
    addChild(renderTexture0);

    return true;
}
```

![]()

![]()
# Comments
- godspeed1024 added comment:
  The original picture:
  ![](http://www.cocos2d-x.org/attachments/3103/pulsar0.png)

Final content of render texture:
![](http://www.cocos2d-x.org/attachments/3104/bug0.png)

**Comment by pandamicro** [comment]
Not reported for v3, close

**Comment by fred1024** [comment]
Sadly I think I must report to you that this bug is not fixed.. in cocos 3

just trying to copy one render texture to another one each frame.
frame 0: render a simple sprite to RTa (then dispose it, not used any more)
frame 1: RTa to RTb
frame 2: RTb to RTa
frame 3: RTa to RTb
frame 4: ...
till the end of times

Of course the interest (in case you wonder why i would do that) is to apply a specific shader between the RT copies to do really nice effects ... well known technique and a real pitty it's messed up in cocos :(

without applying any shaders or transforms ... here are my results ..

after 10 to 20 frames:
![img_0365](https://cloud.githubusercontent.com/assets/1607568/12646950/3881fd5e-c5d3-11e5-83eb-16e13de26d3f.jpg)


after 50 to 60 frames
![img_0368](https://cloud.githubusercontent.com/assets/1607568/12646997/6772c22e-c5d3-11e5-869c-2ed231cd3098.jpg)
