### ISSUE TITLE
Mouse button defines in CCEventMouse.h

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8414]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/4854). It was created at 2014/04/15 11:11:01 +0000
# Description

CCEventMouse.h contains defines for the mouse buttons:

```
#define MOUSE_BUTTON_LEFT       0
#define MOUSE_BUTTON_RIGHT      1
#define MOUSE_BUTTON_MIDDLE     2
#define MOUSE_BUTTON_4          3
#define MOUSE_BUTTON_5          4
#define MOUSE_BUTTON_6          5
#define MOUSE_BUTTON_7          6
#define MOUSE_BUTTON_8          7
```

These defines are outside of the cocos2d namespace, which can lead to conflicts.

They should be moved into the namespace (by moving NS_CC_BEGIN to the line above the defines).

I also wonder about the use of defines, wouldn't they be better of in a MouseButtons enum for example?

Kind regards,
Michaël
- MFHSchoonbrood added comment:
  Here's my proposed solution:

```
#include "CCEvent.h"

NS_CC_BEGIN

enum MouseButtons
{
    MOUSE_BUTTON_LEFT   = 0,
    MOUSE_BUTTON_RIGHT,
    MOUSE_BUTTON_MIDDLE,
    MOUSE_BUTTON_4,
    MOUSE_BUTTON_5,
    MOUSE_BUTTON_6,
    MOUSE_BUTTON_7,
    MOUSE_BUTTON_8
};

class EventMouse : public Event
```

I can send the file to if you prefer...

Kind regards,
Michaël
- dumganhar added comment:
  It seems better. But i think we could make it even better by using `enum class`

``` c++
enum class MouseButton
{
    LEFT,
    RIGHT,
    MIDDLE,
    _4,
    _5,
    _6,
...
};

// When using it
MouseButton::LEFT
MouseButton::_4

```
- MFHSchoonbrood added comment:
  That would make it even more in style with the v3 release, I like it.

**Comment by kompjoefriek** [comment]
Would you consider either of these suggestions for v4?

**Comment by razermirtz** [comment]
i want to try , http://www.ibetvip.com/ , http://www.dosenpoker.com/ , http://www.iopoker.com/ , http://www.santaipoker.com/ , http://www.prediksibos.com/ , http://www.panasqq.com/ , http://www.situsdaftarpoker.com/ , http://www.daftar.poker/ , http://www.memberqq.poker/ , http://www.1001togel.com/ , http://www.agenpoker99.net/ , http://www.daftarsbobetbca.asia/ , http://www.agendomino88.net/ , http://www.pokerandroid88.net/ , http://www.bandarpoker88.net/ , http://www.selerapoker.com/ , http://www.303situspoker.com/ , http://www.pokerdp.com/ , http://www.dominoandroid.net/ , http://www.sakurapoker.net/

**Comment by kompjoefriek** [comment]
@minggo This issue is over 2 years old now, but still relevant because those defines remain unchanged. I would still very much like to do the changes as @dumganhar suggested in the original topic, create an _enum class_ to put those values in.

I'm willing to create the pull-request for it, just as long as it is clear what is expected (for what branch, and in what format the change should be).

**Comment by minggo** [comment]
@kompjoefriek i think it is an outdate issue. Now coocs2d-x uses GLFW for desk platforms, and it uses `GLFW_MOUSE_BUTTON_LEFT` internally. And i also searched the source codes of cocos2d-x, and no any codes uses these macros. So i think i can remove these macros.

I will close this issue. If you have any problem, please let me know. Thanks.

**Comment by radman0x** [comment]
@minggo this isn't an outdated issue. The defines in question still very much exist in version 3.13 in ``CCEventMouse.h`` lines 32-39. Regardless of what cocos is using internally it needs to specify publicly to a client what the codes are. Otherwise how are they to know which number correlates to which mouse button? What I'd like to see is an ``enum class`` in ``EventMouse`` that defines the button mappings, similar to the ``MouseEventType`` that already exists.

For the time being I can use the GLFW mappings through secretly knowing that's the implementation but it's not the appropriate way of doing it.

**Comment by minggo** [comment]
@radman0x could you please create a new issue?

**Comment by radman0x** [comment]
Sure thing, I'll see about putting a PR up for the suggested changes too.

**Comment by radman0x** [comment]
New issue and PR are both up, at #17357 and #17358 respectively. @minggo let me know if there is anything else I should do and some comments on the changes would be great if possible.
