### ISSUE TITLE
Sprite3D's rendering order problem with material transparency

### ISSUE THREAD

**Issue by cpascal** [cocos2d/cocos2d-x#9062]
I have 3D characters(Sprite3D, mesh material have transparency) within complex  UI widgets..

For simple example,
  Root
    + Dialog background
    + Character (Sprite3D, mesh material have transparency) 
    + Another Dialog is overlapped the character partially

But the character renders last because cocos2d-x 3.x rendering pipeline (Renderer::render() function) renders with "all opaque RenderQueue --> all transparent RenderQueue" sequence.
So the problem can't be solved with setGlobalZOrder.

I think it should be programmable in the source code if programmer want the Sprite3D to avoid transparent RenderQueue.

Currently I solved this problem by adding 'useTransparencyRenderQueue' boolean membervariable to Sprite3D. ( I also have used Node::setVertexZ() function before, but the solution was not simple<anyway possible> with complex UI.. )

Do you have any better solution?

**Comment by minggo** [comment]
@super626
Could you please take a look?

**Comment by super626** [comment]
@cpascal 
@minggo 
Thanks.

You would better create another camera, and have this camera see the transparent Sprite3D.

The camera can be same as default camera. Sample code is,
auto camera = Camera::create();
camera->setCameraFlag(CameraFlag::USER1);
addChild(camera);
sprite->setCameraMask((unsigned short)CameraFlag::USER1);

Then it should work. Because the default camera is rendered at last, and your UI is seen be the default camera.

**Comment by minggo** [comment]
@cpascal 
Have you resolved the issue?

**Comment by cpascal** [comment]
@minggo
@super626
Thank you very much. I'm sorry for late response.
I'm refactoring my ui framework to the Camera method today.
