### ISSUE TITLE
change python to python2

### ISSUE THREAD

**Issue by kosl90** [cocos2d/cocos2d-x#9319]
this is an advice, I hope you guys to change python to python2 on all the shebang, this will be much more friendly to those poeple who use python3 as the major python interpreter. especially for unix like users.

**Comment by walzer** [comment]
Currently we're using Python 2.7.5. 
What do you mean by `python2`?

**Comment by kosl90** [comment]
现在很多系统会同时使用python3和python2两个大版本，以ubuntu为例，在/usr/bin/下会安装python3.4或者python2.7之类的可执行文件，但是处于兼容性和易用性等问题的考虑，还会提供一些软连接指向这些真正的可执行程序，例如python、python2、python3。

![python-linux](https://cloud.githubusercontent.com/assets/1311476/7347225/e860bfa6-ed18-11e4-95b4-e92df7160e3a.png)

当调用python这个命令的时候可能是python2也可能是python3，如果将python2作为默认版本时python则是指向python2.7这个可执行文件，反之则指向python3.4这个可执行文件。

因为python2和python3存在不兼容的问题，因此直接使用python作为shebang的解释程序可能会在将python3作为默认python的人群中出现问题。

这条issue是建议将文件中的/usr/bin/env python改为/usr/bin/env python2这样会更有好一点

**Comment by silverweed** [comment]
Thumbs up. Modern Linux distros (e.g. Arch) alias  `python` to Python 3, therefore all the scripts which require Python 2 fail. Even worse, the shebangs contain the hardcoded  `/usr/bin/python` rather than  `/usr/bin/env python`, so there is no clean way to tell the scripts to use Python 2.

This problem would be trivially fixed by using  `#!/usr/bin/python2` in the shebang.

**Comment by minggo** [comment]
Now cocos will detect python version and print error message if the version is wrong. And we can not assume all developers use python2 to refer to correctly version, so close this issue.
