### ISSUE TITLE
LayerColor could be effected by Android theme

### ISSUE THREAD

**Issue by NewCai** [cocos2d/cocos2d-x#9376]
I covered a Layer by a semi-transparent LayerColor.

```
    auto layerColor = LayerColor::create(Color4B(150, 150, 150, 150));
    this->addChild(layerColor, 10);
```

Everything just looked as expected as below when I used a default theme on Android.
![screenshot_2014-12-04-17-21-35](https://cloud.githubusercontent.com/assets/3471662/5296095/fd59abac-7bda-11e4-876f-929c07e92361.png)

But the weird thing happened after I changed the theme to

```
android:theme="@android:style/Theme.Wallpaper.NoTitleBar.Fullscreen"
```

LayerColor was rendered with my wallpaer!

![screenshot_2014-12-04-17-22-521](https://cloud.githubusercontent.com/assets/3471662/5296105/2935d624-7bdb-11e4-8c9a-b46e57aa222c.png)

I reproduced this problem on all Android machines I have. And 2.2.3 version has no problem.

**Comment by NewCai** [comment]
Does nobody care this bug? It really troubled us :sob:

**Comment by ghost** [comment]
@NewCai  What's your purpose by changing the android:theme to Theme.Wallpaper.NoTitleBar.Fullscreen?  In fact I think the behavior is right for you modify and the behavior of version 2.2.3  was wrong instead. And it is not caused by LayerColor, the real reason is the alpha value--if you do sprite->setOpacity(128) you will also see the same "proplem", and the code make the new version different from old version is（in file Cocos2dxActivity.java, method `public Cocos2dxGLSurfaceView onCreateView()` ）:
`if(this.glContextAttrs[3] > 0) glSurfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT);`

**Comment by NewCai** [comment]
@huangshiwu We changed the theme because there is a short period of time of black screen when you start a game on android. And I found the time was uncontrolled(OpenGL part is initializing I guess). Changing the theme to theme.Wallpaper.NoTitleBar.Fullscreen could make screen transition more fluent at the beginning.BTW,Our splash screen is white, so the black screen at the beginning is very obvious.
Maybe the behavior of version 2.2.3 is wrong. We can benefit from it :smile:
