### ISSUE TITLE
isMaxLengthEnabled handling in UITextField::setString

### ISSUE THREAD

**Issue by herojia2021** [cocos2d/cocos2d-x#9507]
in cocos3.2 , if i setMaxLength of textField to 5, then if the textfield already have "abc" and i setText with "def" 
it will be a assert of access out of arraybound.

i findout cocs3.3 have a little change in setText implement, getSubStringOfUTF8String avoid the assert

but actually, why the code compare the maxlimit with length of "abc" plus "def", it should just compare
maxlimit with "def", then the block of if( total > max) will not enter, am i right?

**Comment by zilongshanren** [comment]
@Japarazzi 
Thanks, I think you are right here. Could you send a PR to resolve this issue?

**Comment by pandamicro** [comment]
@qiululu Please take a look at this issue

**Comment by qiululu** [comment]
two things: 
first you should setMaxLengthEnabled before you use setText function ,  second  setText is a deprecated function,  but you and still use it at present. 
I've added test code for it, and it works with no crash , and I suggest you use setString function instead of setText , if it still has problem, contact us and you can give further infomation for it, such as in which  case it will cause this problem.  and note that I was talking about the latest version of coco-x at the version of 3.7
