### ISSUE TITLE
LabelTTF display unexpectedly

### ISSUE THREAD

**Issue by KyoChen** [cocos2d/cocos2d-x#9559]
issue: Words of label created with TTF display unexpectedly. Look at the attached picture, part of each word doses not displayed, especially the edge of rounded part of 'b'/'e'/'2'/'1'. 
reason: The situation may be caused by error or offset of textureRect of sprite 
advice: Add 2 px width/height padding(empty) among words on texture that created with TTF. Just like Glyph Padding option of GlyphDesigner.
If you guys need the TTF, ask me by e-mail. kyochen@qq.com
![img_2077](https://cloud.githubusercontent.com/assets/4214213/5503723/855f426a-87b5-11e4-9480-1b2b45adaef0.PNG)

**Comment by jminht** [comment]
did you fix this ?

**Comment by walzer** [comment]
Close this issue because:
- inactive for +3 months
- insufficient info：engine version, target platform and platform version. 
  We have refactored `LabelTTF` using the new `Label` in v3.0. So I can't recognize if your bug is caused by the old `LabelTTF` or new one unless we have an engine version here.

If the bug still existing in v3.4 or later, please report another issue here. You're welcome @KyoChen , thanks for your lots feedback and bug reports!
