### ISSUE TITLE
cannot set or read volume on win32

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/cocos2d-x#9910]
Using Simple Audio engine, it is not possible to set or read the volume on win32, because it is not implemented.

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/audio/win32/SimpleAudioEngine.cpp#L262

**Comment by walzer** [comment]
My idea is to wrap `AudioEngine` into `SimpleAudioEngine` in v3.8. The pros are:
- Many developers like our new `AudioEngine`, which is much more powerful, especially the callback function.
- `AudioEngine` already avoid the bug of Android 5.0.x `SoundPool.preload()`, which will cause `SimpleAudioEngine::playEffect()`. Many developers in China are moving to `AudioEngine` because they want to avoid this bug in Android 5.0.x
- We don't need to maintain 2 audio implementations in the future.

So, to get the volume on win32, my ideas are:
- Implement `AudioEngine` on the rest platforms, as #11563 described.
- Wrap `AudioEngine` to `SimpleAudioEngine`, so we have solid `getVolume` on win32, as #9911 described.
