### ISSUE TITLE
Controller support for Win/Mac/Linux

### ISSUE THREAD

**Issue by darkdukey** [cocos2d/cocos2d-x#9912]
Seems some developer already did it, http://cocos2d-x.org/issues/4689

**Comment by darkdukey** [comment]
And their game is greenlit on steam
http://discuss.cocos2d-x.org/t/a-quiver-of-crows-steam-greenlight/19325

**Comment by FryDay** [comment]
This would be extremely useful and in my opinion, necessary. I would love to use Cocos2d-x for Steam games, but it isn't really possible without this.

**Comment by walzer** [comment]
In my idea, cocos2d-x should focus on "mobile first".
Desktop platforms are majorly the development platform and debug platform. 
To prevent scope spreading, I wouldn't add new features for desktop platforms only, unless we have more human resources.

**Comment by Sheado** [comment]
Hi @walzer,

In the US and Europe, Steam is extremely popular. 
You can see current stats here: http://store.steampowered.com/stats/ 
Last I checked, they are at 125m users and difference between Steam and mobile is that every person on Steam is a gamer and almost all of them are paying customers - many of whom are happy to still purchase premium games instead of playing F2P games. 

If cocos2d-x doesn't support desktop platforms, I think that western developers may be forced to choose another platform such as Unity instead. 

I'm sure you guys are spread thin, but some of these new features are being added by the community. I plan to ship my next game on Steam with controller support - it would be nice if my contributions are included so that I don't have to keep working off of a separate branch, which nobody will gain from or contribute to.

**Comment by FryDay** [comment]
Good morning @walzer,

Why even support desktop platforms at all then? It's a bit misleading to have OSX, Linux, and Windows options and then treat them as 2nd class citizens, isn't it? Your comments make me REALLY nervous to use Cocos2d-x for a commercial desktop game...

**Comment by JOOpdenhoevel** [comment]
And mouse and keyboard events only happen on a PC, so why do you want to stop controller support getting into cocos? (Maybe there will be controllers that you can use with your tablet in the future?)

**Comment by minggo** [comment]
There is not plan to support controller on PC right now, so close this issue.
